package bnfc.abs.Absyn; // Java Package generated by the BNF Converter.

public abstract class Ann_ implements java.io.Serializable {
  public abstract <R,A> R accept(Ann_.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(bnfc.abs.Absyn.AnnNoType p, A arg);
    public R visit(bnfc.abs.Absyn.AnnWithType p, A arg);

  }

}
