package bnfc.abs.Absyn; // Java Package generated by the BNF Converter.

public class AnnDeclaration extends AnnDecl {
  public final ListAnn listann_;
  public final Decl decl_;
  public AnnDeclaration(ListAnn p1, Decl p2) { listann_ = p1; decl_ = p2; }

  public <R,A> R accept(bnfc.abs.Absyn.AnnDecl.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof bnfc.abs.Absyn.AnnDeclaration) {
      bnfc.abs.Absyn.AnnDeclaration x = (bnfc.abs.Absyn.AnnDeclaration)o;
      return this.listann_.equals(x.listann_) && this.decl_.equals(x.decl_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.listann_.hashCode())+this.decl_.hashCode();
  }


}
