package bnfc.abs.Absyn; // Java Package generated by the BNF Converter.

public class AnnNoType extends Ann_ {
  public final PureExp pureexp_;
  public AnnNoType(PureExp p1) { pureexp_ = p1; }

  public <R,A> R accept(bnfc.abs.Absyn.Ann_.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof bnfc.abs.Absyn.AnnNoType) {
      bnfc.abs.Absyn.AnnNoType x = (bnfc.abs.Absyn.AnnNoType)o;
      return this.pureexp_.equals(x.pureexp_);
    }
    return false;
  }

  public int hashCode() {
    return this.pureexp_.hashCode();
  }


}
