package bnfc.abs.Absyn; // Java Package generated by the BNF Converter.

public class Annotation extends Ann {
  public final Ann_ ann__;
  public Annotation(Ann_ p1) { ann__ = p1; }

  public <R,A> R accept(bnfc.abs.Absyn.Ann.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof bnfc.abs.Absyn.Annotation) {
      bnfc.abs.Absyn.Annotation x = (bnfc.abs.Absyn.Annotation)o;
      return this.ann__.equals(x.ann__);
    }
    return false;
  }

  public int hashCode() {
    return this.ann__.hashCode();
  }


}
