package bnfc.abs.Absyn; // Java Package generated by the BNF Converter.

public class AnnStatement extends AnnStm {
  public final ListAnn listann_;
  public final Stm stm_;
  public AnnStatement(ListAnn p1, Stm p2) { listann_ = p1; stm_ = p2; }

  public <R,A> R accept(bnfc.abs.Absyn.AnnStm.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof bnfc.abs.Absyn.AnnStatement) {
      bnfc.abs.Absyn.AnnStatement x = (bnfc.abs.Absyn.AnnStatement)o;
      return this.listann_.equals(x.listann_) && this.stm_.equals(x.stm_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.listann_.hashCode())+this.stm_.hashCode();
  }


}
