package bnfc.abs.Absyn; // Java Package generated by the BNF Converter.

public class AnnWithType extends Ann_ {
  public final T t_;
  public final PureExp pureexp_;
  public AnnWithType(T p1, PureExp p2) { t_ = p1; pureexp_ = p2; }

  public <R,A> R accept(bnfc.abs.Absyn.Ann_.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof bnfc.abs.Absyn.AnnWithType) {
      bnfc.abs.Absyn.AnnWithType x = (bnfc.abs.Absyn.AnnWithType)o;
      return this.t_.equals(x.t_) && this.pureexp_.equals(x.pureexp_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.t_.hashCode())+this.pureexp_.hashCode();
  }


}
