package bnfc.abs.Absyn; // Java Package generated by the BNF Converter.

public class AnyFromImport extends Import {
  public final IsForeign isforeign_;
  public final ListQA listqa_;
  public final QU qu_;
  public AnyFromImport(IsForeign p1, ListQA p2, QU p3) { isforeign_ = p1; listqa_ = p2; qu_ = p3; }

  public <R,A> R accept(bnfc.abs.Absyn.Import.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof bnfc.abs.Absyn.AnyFromImport) {
      bnfc.abs.Absyn.AnyFromImport x = (bnfc.abs.Absyn.AnyFromImport)o;
      return this.isforeign_.equals(x.isforeign_) && this.listqa_.equals(x.listqa_) && this.qu_.equals(x.qu_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(this.isforeign_.hashCode())+this.listqa_.hashCode())+this.qu_.hashCode();
  }


}
