package bnfc.abs.Absyn; // Java Package generated by the BNF Converter.

public class AnyFromExport extends Export {
  public final ListQA listqa_;
  public final QU qu_;
  public AnyFromExport(ListQA p1, QU p2) { listqa_ = p1; qu_ = p2; }

  public <R,A> R accept(bnfc.abs.Absyn.Export.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof bnfc.abs.Absyn.AnyFromExport) {
      bnfc.abs.Absyn.AnyFromExport x = (bnfc.abs.Absyn.AnyFromExport)o;
      return this.listqa_.equals(x.listqa_) && this.qu_.equals(x.qu_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.listqa_.hashCode())+this.qu_.hashCode();
  }


}
