package bnfc.abs.Absyn; // Java Package generated by the BNF Converter.

public class AnyImport extends Import {
  public final IsForeign isforeign_;
  public final ListQA listqa_;
  public AnyImport(IsForeign p1, ListQA p2) { isforeign_ = p1; listqa_ = p2; }

  public <R,A> R accept(bnfc.abs.Absyn.Import.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof bnfc.abs.Absyn.AnyImport) {
      bnfc.abs.Absyn.AnyImport x = (bnfc.abs.Absyn.AnyImport)o;
      return this.isforeign_.equals(x.isforeign_) && this.listqa_.equals(x.listqa_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.isforeign_.hashCode())+this.listqa_.hashCode();
  }


}
