package bnfc.abs.Absyn; // Java Package generated by the BNF Converter.

public abstract class AnyIdent implements java.io.Serializable {
  public abstract <R,A> R accept(AnyIdent.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(bnfc.abs.Absyn.AnyIden p, A arg);
    public R visit(bnfc.abs.Absyn.AnyTyIden p, A arg);

  }

}
