package bnfc.abs.Absyn; // Java Package generated by the BNF Converter.

public class AsyncMethCall extends EffExp {
  public final PureExp pureexp_;
  public final String l_;
  public final ListPureExp listpureexp_;
  public AsyncMethCall(PureExp p1, String p2, ListPureExp p3) { pureexp_ = p1; l_ = p2; listpureexp_ = p3; }

  public <R,A> R accept(bnfc.abs.Absyn.EffExp.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof bnfc.abs.Absyn.AsyncMethCall) {
      bnfc.abs.Absyn.AsyncMethCall x = (bnfc.abs.Absyn.AsyncMethCall)o;
      return this.pureexp_.equals(x.pureexp_) && this.l_.equals(x.l_) && this.listpureexp_.equals(x.listpureexp_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(this.pureexp_.hashCode())+this.l_.hashCode())+this.listpureexp_.hashCode();
  }


}
