package bnfc.abs.Absyn; // Java Package generated by the BNF Converter.

public abstract class AwaitGuard implements java.io.Serializable {
  public abstract <R,A> R accept(AwaitGuard.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(bnfc.abs.Absyn.GFut p, A arg);
    public R visit(bnfc.abs.Absyn.GFutField p, A arg);
    public R visit(bnfc.abs.Absyn.GExp p, A arg);
    public R visit(bnfc.abs.Absyn.GAnd p, A arg);
    public R visit(bnfc.abs.Absyn.GDuration p, A arg);

  }

}
