package bnfc.abs.Absyn; // Java Package generated by the BNF Converter.

public class CaseBranc extends CaseBranch {
  public final Pattern pattern_;
  public final PureExp pureexp_;
  public CaseBranc(Pattern p1, PureExp p2) { pattern_ = p1; pureexp_ = p2; }

  public <R,A> R accept(bnfc.abs.Absyn.CaseBranch.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof bnfc.abs.Absyn.CaseBranc) {
      bnfc.abs.Absyn.CaseBranc x = (bnfc.abs.Absyn.CaseBranc)o;
      return this.pattern_.equals(x.pattern_) && this.pureexp_.equals(x.pureexp_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.pattern_.hashCode())+this.pureexp_.hashCode();
  }


}
