package bnfc.abs.Absyn; // Java Package generated by the BNF Converter.

public abstract class ClassBody implements java.io.Serializable {
  public abstract <R,A> R accept(ClassBody.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(bnfc.abs.Absyn.FieldClassBody p, A arg);
    public R visit(bnfc.abs.Absyn.FieldAssignClassBody p, A arg);
    public R visit(bnfc.abs.Absyn.MethClassBody p, A arg);

  }

}
