package bnfc.abs.Absyn; // Java Package generated by the BNF Converter.

public abstract class ConstrIdent implements java.io.Serializable {
  public abstract <R,A> R accept(ConstrIdent.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(bnfc.abs.Absyn.SinglConstrIdent p, A arg);
    public R visit(bnfc.abs.Absyn.ParamConstrIdent p, A arg);

  }

}
