package bnfc.abs.Absyn; // Java Package generated by the BNF Converter.

public class DataParDecl extends Decl {
  public final String uident_;
  public final ListUIdent listuident_;
  public final ListConstrIdent listconstrident_;
  public DataParDecl(String p1, ListUIdent p2, ListConstrIdent p3) { uident_ = p1; listuident_ = p2; listconstrident_ = p3; }

  public <R,A> R accept(bnfc.abs.Absyn.Decl.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof bnfc.abs.Absyn.DataParDecl) {
      bnfc.abs.Absyn.DataParDecl x = (bnfc.abs.Absyn.DataParDecl)o;
      return this.uident_.equals(x.uident_) && this.listuident_.equals(x.listuident_) && this.listconstrident_.equals(x.listconstrident_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(this.uident_.hashCode())+this.listuident_.hashCode())+this.listconstrident_.hashCode();
  }


}
