package bnfc.abs.Absyn; // Java Package generated by the BNF Converter.

public class DClassParImplements extends Decl {
  public final String u_;
  public final ListFormalPar listformalpar_;
  public final ListQU listqu_;
  public final ListClassBody listclassbody_1, listclassbody_2;
  public final MaybeBlock maybeblock_;
  public DClassParImplements(String p1, ListFormalPar p2, ListQU p3, ListClassBody p4, MaybeBlock p5, ListClassBody p6) { u_ = p1; listformalpar_ = p2; listqu_ = p3; listclassbody_1 = p4; maybeblock_ = p5; listclassbody_2 = p6; }

  public <R,A> R accept(bnfc.abs.Absyn.Decl.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof bnfc.abs.Absyn.DClassParImplements) {
      bnfc.abs.Absyn.DClassParImplements x = (bnfc.abs.Absyn.DClassParImplements)o;
      return this.u_.equals(x.u_) && this.listformalpar_.equals(x.listformalpar_) && this.listqu_.equals(x.listqu_) && this.listclassbody_1.equals(x.listclassbody_1) && this.maybeblock_.equals(x.maybeblock_) && this.listclassbody_2.equals(x.listclassbody_2);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(37*(37*(37*(this.u_.hashCode())+this.listformalpar_.hashCode())+this.listqu_.hashCode())+this.listclassbody_1.hashCode())+this.maybeblock_.hashCode())+this.listclassbody_2.hashCode();
  }


}
