package bnfc.abs.Absyn; // Java Package generated by the BNF Converter.

public class DClassImplements extends Decl {
  public final String u_;
  public final ListQU listqu_;
  public final ListClassBody listclassbody_1, listclassbody_2;
  public final MaybeBlock maybeblock_;
  public DClassImplements(String p1, ListQU p2, ListClassBody p3, MaybeBlock p4, ListClassBody p5) { u_ = p1; listqu_ = p2; listclassbody_1 = p3; maybeblock_ = p4; listclassbody_2 = p5; }

  public <R,A> R accept(bnfc.abs.Absyn.Decl.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof bnfc.abs.Absyn.DClassImplements) {
      bnfc.abs.Absyn.DClassImplements x = (bnfc.abs.Absyn.DClassImplements)o;
      return this.u_.equals(x.u_) && this.listqu_.equals(x.listqu_) && this.listclassbody_1.equals(x.listclassbody_1) && this.maybeblock_.equals(x.maybeblock_) && this.listclassbody_2.equals(x.listclassbody_2);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(37*(37*(this.u_.hashCode())+this.listqu_.hashCode())+this.listclassbody_1.hashCode())+this.maybeblock_.hashCode())+this.listclassbody_2.hashCode();
  }


}
