package bnfc.abs.Absyn; // Java Package generated by the BNF Converter.

public class DDataPoly extends Decl {
  public final String u_;
  public final ListU listu_;
  public final ListConstrIdent listconstrident_;
  public DDataPoly(String p1, ListU p2, ListConstrIdent p3) { u_ = p1; listu_ = p2; listconstrident_ = p3; }

  public <R,A> R accept(bnfc.abs.Absyn.Decl.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof bnfc.abs.Absyn.DDataPoly) {
      bnfc.abs.Absyn.DDataPoly x = (bnfc.abs.Absyn.DDataPoly)o;
      return this.u_.equals(x.u_) && this.listu_.equals(x.listu_) && this.listconstrident_.equals(x.listconstrident_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(this.u_.hashCode())+this.listu_.hashCode())+this.listconstrident_.hashCode();
  }


}
