package bnfc.abs.Absyn; // Java Package generated by the BNF Converter.

public class DData extends Decl {
  public final String u_;
  public final ListConstrIdent listconstrident_;
  public DData(String p1, ListConstrIdent p2) { u_ = p1; listconstrident_ = p2; }

  public <R,A> R accept(bnfc.abs.Absyn.Decl.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof bnfc.abs.Absyn.DData) {
      bnfc.abs.Absyn.DData x = (bnfc.abs.Absyn.DData)o;
      return this.u_.equals(x.u_) && this.listconstrident_.equals(x.listconstrident_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.u_.hashCode())+this.listconstrident_.hashCode();
  }


}
