package bnfc.abs.Absyn; // Java Package generated by the BNF Converter.

public abstract class Decl implements java.io.Serializable {
  public abstract <R,A> R accept(Decl.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(bnfc.abs.Absyn.DType p, A arg);
    public R visit(bnfc.abs.Absyn.DTypePoly p, A arg);
    public R visit(bnfc.abs.Absyn.DData p, A arg);
    public R visit(bnfc.abs.Absyn.DDataPoly p, A arg);
    public R visit(bnfc.abs.Absyn.DFun p, A arg);
    public R visit(bnfc.abs.Absyn.DFunPoly p, A arg);
    public R visit(bnfc.abs.Absyn.DInterf p, A arg);
    public R visit(bnfc.abs.Absyn.DExtends p, A arg);
    public R visit(bnfc.abs.Absyn.DClass p, A arg);
    public R visit(bnfc.abs.Absyn.DClassPar p, A arg);
    public R visit(bnfc.abs.Absyn.DClassImplements p, A arg);
    public R visit(bnfc.abs.Absyn.DClassParImplements p, A arg);
    public R visit(bnfc.abs.Absyn.DException p, A arg);

  }

}
