package bnfc.abs.Absyn; // Java Package generated by the BNF Converter.

public class DExtends extends Decl {
  public final String u_;
  public final ListQU listqu_;
  public final ListMethSig listmethsig_;
  public DExtends(String p1, ListQU p2, ListMethSig p3) { u_ = p1; listqu_ = p2; listmethsig_ = p3; }

  public <R,A> R accept(bnfc.abs.Absyn.Decl.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof bnfc.abs.Absyn.DExtends) {
      bnfc.abs.Absyn.DExtends x = (bnfc.abs.Absyn.DExtends)o;
      return this.u_.equals(x.u_) && this.listqu_.equals(x.listqu_) && this.listmethsig_.equals(x.listmethsig_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(this.u_.hashCode())+this.listqu_.hashCode())+this.listmethsig_.hashCode();
  }


}
