package bnfc.abs.Absyn; // Java Package generated by the BNF Converter.

public class DFunPoly extends Decl {
  public final T t_;
  public final String l_;
  public final ListU listu_;
  public final ListFormalPar listformalpar_;
  public final FunBody funbody_;
  public DFunPoly(T p1, String p2, ListU p3, ListFormalPar p4, FunBody p5) { t_ = p1; l_ = p2; listu_ = p3; listformalpar_ = p4; funbody_ = p5; }

  public <R,A> R accept(bnfc.abs.Absyn.Decl.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof bnfc.abs.Absyn.DFunPoly) {
      bnfc.abs.Absyn.DFunPoly x = (bnfc.abs.Absyn.DFunPoly)o;
      return this.t_.equals(x.t_) && this.l_.equals(x.l_) && this.listu_.equals(x.listu_) && this.listformalpar_.equals(x.listformalpar_) && this.funbody_.equals(x.funbody_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(37*(37*(this.t_.hashCode())+this.l_.hashCode())+this.listu_.hashCode())+this.listformalpar_.hashCode())+this.funbody_.hashCode();
  }


}
