package bnfc.abs.Absyn; // Java Package generated by the BNF Converter.

public class DFun extends Decl {
  public final T t_;
  public final String l_;
  public final ListFormalPar listformalpar_;
  public final FunBody funbody_;
  public DFun(T p1, String p2, ListFormalPar p3, FunBody p4) { t_ = p1; l_ = p2; listformalpar_ = p3; funbody_ = p4; }

  public <R,A> R accept(bnfc.abs.Absyn.Decl.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof bnfc.abs.Absyn.DFun) {
      bnfc.abs.Absyn.DFun x = (bnfc.abs.Absyn.DFun)o;
      return this.t_.equals(x.t_) && this.l_.equals(x.l_) && this.listformalpar_.equals(x.listformalpar_) && this.funbody_.equals(x.funbody_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(37*(this.t_.hashCode())+this.l_.hashCode())+this.listformalpar_.hashCode())+this.funbody_.hashCode();
  }


}
