package bnfc.abs.Absyn; // Java Package generated by the BNF Converter.

public class DInterf extends Decl {
  public final String u_;
  public final ListMethSig listmethsig_;
  public DInterf(String p1, ListMethSig p2) { u_ = p1; listmethsig_ = p2; }

  public <R,A> R accept(bnfc.abs.Absyn.Decl.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof bnfc.abs.Absyn.DInterf) {
      bnfc.abs.Absyn.DInterf x = (bnfc.abs.Absyn.DInterf)o;
      return this.u_.equals(x.u_) && this.listmethsig_.equals(x.listmethsig_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.u_.hashCode())+this.listmethsig_.hashCode();
  }


}
