package bnfc.abs.Absyn; // Java Package generated by the BNF Converter.

public class DTypePoly extends Decl {
  public final String u_;
  public final ListU listu_;
  public final T t_;
  public DTypePoly(String p1, ListU p2, T p3) { u_ = p1; listu_ = p2; t_ = p3; }

  public <R,A> R accept(bnfc.abs.Absyn.Decl.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof bnfc.abs.Absyn.DTypePoly) {
      bnfc.abs.Absyn.DTypePoly x = (bnfc.abs.Absyn.DTypePoly)o;
      return this.u_.equals(x.u_) && this.listu_.equals(x.listu_) && this.t_.equals(x.t_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(this.u_.hashCode())+this.listu_.hashCode())+this.t_.hashCode();
  }


}
