package bnfc.abs.Absyn; // Java Package generated by the BNF Converter.

public class DType extends Decl {
  public final String u_;
  public final T t_;
  public DType(String p1, T p2) { u_ = p1; t_ = p2; }

  public <R,A> R accept(bnfc.abs.Absyn.Decl.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof bnfc.abs.Absyn.DType) {
      bnfc.abs.Absyn.DType x = (bnfc.abs.Absyn.DType)o;
      return this.u_.equals(x.u_) && this.t_.equals(x.t_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.u_.hashCode())+this.t_.hashCode();
  }


}
