package bnfc.abs.Absyn; // Java Package generated by the BNF Converter.

public class ECase extends PureExp {
  public final PureExp pureexp_;
  public final ListECaseBranch listecasebranch_;
  public ECase(PureExp p1, ListECaseBranch p2) { pureexp_ = p1; listecasebranch_ = p2; }

  public <R,A> R accept(bnfc.abs.Absyn.PureExp.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof bnfc.abs.Absyn.ECase) {
      bnfc.abs.Absyn.ECase x = (bnfc.abs.Absyn.ECase)o;
      return this.pureexp_.equals(x.pureexp_) && this.listecasebranch_.equals(x.listecasebranch_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.pureexp_.hashCode())+this.listecasebranch_.hashCode();
  }


}
