package bnfc.abs.Absyn; // Java Package generated by the BNF Converter.

public abstract class ECaseBranch implements java.io.Serializable {
  public abstract <R,A> R accept(ECaseBranch.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(bnfc.abs.Absyn.ECaseB p, A arg);

  }

}
