package bnfc.abs.Absyn; // Java Package generated by the BNF Converter.

public class ELet extends PureExp {
  public final FormalPar formalpar_;
  public final PureExp pureexp_1, pureexp_2;
  public ELet(FormalPar p1, PureExp p2, PureExp p3) { formalpar_ = p1; pureexp_1 = p2; pureexp_2 = p3; }

  public <R,A> R accept(bnfc.abs.Absyn.PureExp.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof bnfc.abs.Absyn.ELet) {
      bnfc.abs.Absyn.ELet x = (bnfc.abs.Absyn.ELet)o;
      return this.formalpar_.equals(x.formalpar_) && this.pureexp_1.equals(x.pureexp_1) && this.pureexp_2.equals(x.pureexp_2);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(this.formalpar_.hashCode())+this.pureexp_1.hashCode())+this.pureexp_2.hashCode();
  }


}
