package bnfc.abs.Absyn; // Java Package generated by the BNF Converter.

public class EmptyConstrType extends ConstrType {
  public final Type type_;
  public EmptyConstrType(Type p1) { type_ = p1; }

  public <R,A> R accept(bnfc.abs.Absyn.ConstrType.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof bnfc.abs.Absyn.EmptyConstrType) {
      bnfc.abs.Absyn.EmptyConstrType x = (bnfc.abs.Absyn.EmptyConstrType)o;
      return this.type_.equals(x.type_);
    }
    return false;
  }

  public int hashCode() {
    return this.type_.hashCode();
  }


}
