package bnfc.abs.Absyn; // Java Package generated by the BNF Converter.

public class EmptyConstrType extends ConstrType {
  public final T t_;
  public EmptyConstrType(T p1) { t_ = p1; }

  public <R,A> R accept(bnfc.abs.Absyn.ConstrType.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof bnfc.abs.Absyn.EmptyConstrType) {
      bnfc.abs.Absyn.EmptyConstrType x = (bnfc.abs.Absyn.EmptyConstrType)o;
      return this.t_.equals(x.t_);
    }
    return false;
  }

  public int hashCode() {
    return this.t_.hashCode();
  }


}
