package bnfc.abs.Absyn; // Java Package generated by the BNF Converter.

public class EParamConstr extends PureExp {
  public final QU qu_;
  public final ListPureExp listpureexp_;
  public EParamConstr(QU p1, ListPureExp p2) { qu_ = p1; listpureexp_ = p2; }

  public <R,A> R accept(bnfc.abs.Absyn.PureExp.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof bnfc.abs.Absyn.EParamConstr) {
      bnfc.abs.Absyn.EParamConstr x = (bnfc.abs.Absyn.EParamConstr)o;
      return this.qu_.equals(x.qu_) && this.listpureexp_.equals(x.listpureexp_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.qu_.hashCode())+this.listpureexp_.hashCode();
  }


}
