package bnfc.abs.Absyn; // Java Package generated by the BNF Converter.

public class ExceptionDecl extends Decl {
  public final ConstrIdent constrident_;
  public ExceptionDecl(ConstrIdent p1) { constrident_ = p1; }

  public <R,A> R accept(bnfc.abs.Absyn.Decl.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof bnfc.abs.Absyn.ExceptionDecl) {
      bnfc.abs.Absyn.ExceptionDecl x = (bnfc.abs.Absyn.ExceptionDecl)o;
      return this.constrident_.equals(x.constrident_);
    }
    return false;
  }

  public int hashCode() {
    return this.constrident_.hashCode();
  }


}
