package bnfc.abs.Absyn; // Java Package generated by the BNF Converter.

public class ExpE extends Exp {
  public final EffExp effexp_;
  public ExpE(EffExp p1) { effexp_ = p1; }

  public <R,A> R accept(bnfc.abs.Absyn.Exp.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof bnfc.abs.Absyn.ExpE) {
      bnfc.abs.Absyn.ExpE x = (bnfc.abs.Absyn.ExpE)o;
      return this.effexp_.equals(x.effexp_);
    }
    return false;
  }

  public int hashCode() {
    return this.effexp_.hashCode();
  }


}
