package bnfc.abs.Absyn; // Java Package generated by the BNF Converter.

public abstract class Export implements java.io.Serializable {
  public abstract <R,A> R accept(Export.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(bnfc.abs.Absyn.StarExport p, A arg);
    public R visit(bnfc.abs.Absyn.StarFromExport p, A arg);
    public R visit(bnfc.abs.Absyn.AnyExport p, A arg);
    public R visit(bnfc.abs.Absyn.AnyFromExport p, A arg);

  }

}
