package bnfc.abs.Absyn; // Java Package generated by the BNF Converter.

public class FieldAssignClassBody extends ClassBody {
  public final T t_;
  public final String l_;
  public final PureExp pureexp_;
  public FieldAssignClassBody(T p1, String p2, PureExp p3) { t_ = p1; l_ = p2; pureexp_ = p3; }

  public <R,A> R accept(bnfc.abs.Absyn.ClassBody.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof bnfc.abs.Absyn.FieldAssignClassBody) {
      bnfc.abs.Absyn.FieldAssignClassBody x = (bnfc.abs.Absyn.FieldAssignClassBody)o;
      return this.t_.equals(x.t_) && this.l_.equals(x.l_) && this.pureexp_.equals(x.pureexp_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(this.t_.hashCode())+this.l_.hashCode())+this.pureexp_.hashCode();
  }


}
