package bnfc.abs.Absyn; // Java Package generated by the BNF Converter.

public class FormalParameter extends FormalPar {
  public final T t_;
  public final String l_;
  public FormalParameter(T p1, String p2) { t_ = p1; l_ = p2; }

  public <R,A> R accept(bnfc.abs.Absyn.FormalPar.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof bnfc.abs.Absyn.FormalParameter) {
      bnfc.abs.Absyn.FormalParameter x = (bnfc.abs.Absyn.FormalParameter)o;
      return this.t_.equals(x.t_) && this.l_.equals(x.l_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.t_.hashCode())+this.l_.hashCode();
  }


}
