package bnfc.abs.Absyn; // Java Package generated by the BNF Converter.

public class GAnd extends AwaitGuard {
  public final AwaitGuard awaitguard_1, awaitguard_2;
  public GAnd(AwaitGuard p1, AwaitGuard p2) { awaitguard_1 = p1; awaitguard_2 = p2; }

  public <R,A> R accept(bnfc.abs.Absyn.AwaitGuard.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof bnfc.abs.Absyn.GAnd) {
      bnfc.abs.Absyn.GAnd x = (bnfc.abs.Absyn.GAnd)o;
      return this.awaitguard_1.equals(x.awaitguard_1) && this.awaitguard_2.equals(x.awaitguard_2);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.awaitguard_1.hashCode())+this.awaitguard_2.hashCode();
  }


}
