package bnfc.abs.Absyn; // Java Package generated by the BNF Converter.

public abstract class ImportType implements java.io.Serializable {
  public abstract <R,A> R accept(ImportType.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(bnfc.abs.Absyn.ForeignImport p, A arg);
    public R visit(bnfc.abs.Absyn.NormalImport p, A arg);

  }

}
