package bnfc.abs.Absyn; // Java Package generated by the BNF Converter.

public abstract class IsForeign implements java.io.Serializable {
  public abstract <R,A> R accept(IsForeign.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(bnfc.abs.Absyn.NoForeign p, A arg);
    public R visit(bnfc.abs.Absyn.YesForeign p, A arg);

  }

}
