package bnfc.abs.Absyn; // Java Package generated by the BNF Converter.

public class JustFinally extends MaybeFinally {
  public final AnnStm annstm_;
  public JustFinally(AnnStm p1) { annstm_ = p1; }

  public <R,A> R accept(bnfc.abs.Absyn.MaybeFinally.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof bnfc.abs.Absyn.JustFinally) {
      bnfc.abs.Absyn.JustFinally x = (bnfc.abs.Absyn.JustFinally)o;
      return this.annstm_.equals(x.annstm_);
    }
    return false;
  }

  public int hashCode() {
    return this.annstm_.hashCode();
  }


}
