package bnfc.abs.Absyn; // Java Package generated by the BNF Converter.

public class L_ extends QL {
  public final String l_;
  public L_(String p1) { l_ = p1; }

  public <R,A> R accept(bnfc.abs.Absyn.QL.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof bnfc.abs.Absyn.L_) {
      bnfc.abs.Absyn.L_ x = (bnfc.abs.Absyn.L_)o;
      return this.l_.equals(x.l_);
    }
    return false;
  }

  public int hashCode() {
    return this.l_.hashCode();
  }


}
