package bnfc.abs.Absyn; // Java Package generated by the BNF Converter.

public class LA extends QA {
  public final String l_;
  public LA(String p1) { l_ = p1; }

  public <R,A> R accept(bnfc.abs.Absyn.QA.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof bnfc.abs.Absyn.LA) {
      bnfc.abs.Absyn.LA x = (bnfc.abs.Absyn.LA)o;
      return this.l_.equals(x.l_);
    }
    return false;
  }

  public int hashCode() {
    return this.l_.hashCode();
  }


}
