package bnfc.abs.Absyn; // Java Package generated by the BNF Converter.

public class LFloat extends Literal {
  public final Double double_;
  public LFloat(Double p1) { double_ = p1; }

  public <R,A> R accept(bnfc.abs.Absyn.Literal.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof bnfc.abs.Absyn.LFloat) {
      bnfc.abs.Absyn.LFloat x = (bnfc.abs.Absyn.LFloat)o;
      return this.double_.equals(x.double_);
    }
    return false;
  }

  public int hashCode() {
    return this.double_.hashCode();
  }


}
