package bnfc.abs.Absyn; // Java Package generated by the BNF Converter.

public class LInt extends Literal {
  public final Long integer_;
  public LInt(Long p1) { integer_ = p1; }

  public <R,A> R accept(bnfc.abs.Absyn.Literal.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof bnfc.abs.Absyn.LInt) {
      bnfc.abs.Absyn.LInt x = (bnfc.abs.Absyn.LInt)o;
      return this.integer_.equals(x.integer_);
    }
    return false;
  }

  public int hashCode() {
    return this.integer_.hashCode();
  }


}
