package bnfc.abs.Absyn; // Java Package generated by the BNF Converter.

public class LStr extends Literal {
  public final String string_;
  public LStr(String p1) { string_ = p1; }

  public <R,A> R accept(bnfc.abs.Absyn.Literal.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof bnfc.abs.Absyn.LStr) {
      bnfc.abs.Absyn.LStr x = (bnfc.abs.Absyn.LStr)o;
      return this.string_.equals(x.string_);
    }
    return false;
  }

  public int hashCode() {
    return this.string_.hashCode();
  }


}
