package bnfc.abs.Absyn; // Java Package generated by the BNF Converter.

public class MappedAnn extends Ann {
  public final Literal literal_1, literal_2;
  public MappedAnn(Literal p1, Literal p2) { literal_1 = p1; literal_2 = p2; }

  public <R,A> R accept(bnfc.abs.Absyn.Ann.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof bnfc.abs.Absyn.MappedAnn) {
      bnfc.abs.Absyn.MappedAnn x = (bnfc.abs.Absyn.MappedAnn)o;
      return this.literal_1.equals(x.literal_1) && this.literal_2.equals(x.literal_2);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.literal_1.hashCode())+this.literal_2.hashCode();
  }


}
