package bnfc.abs.Absyn; // Java Package generated by the BNF Converter.

public class MethSignature extends MethSig {
  public final ListAnn listann_;
  public final T t_;
  public final String l_;
  public final ListFormalPar listformalpar_;
  public MethSignature(ListAnn p1, T p2, String p3, ListFormalPar p4) { listann_ = p1; t_ = p2; l_ = p3; listformalpar_ = p4; }

  public <R,A> R accept(bnfc.abs.Absyn.MethSig.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof bnfc.abs.Absyn.MethSignature) {
      bnfc.abs.Absyn.MethSignature x = (bnfc.abs.Absyn.MethSignature)o;
      return this.listann_.equals(x.listann_) && this.t_.equals(x.t_) && this.l_.equals(x.l_) && this.listformalpar_.equals(x.listformalpar_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(37*(this.listann_.hashCode())+this.t_.hashCode())+this.l_.hashCode())+this.listformalpar_.hashCode();
  }


}
