package bnfc.abs.Absyn; // Java Package generated by the BNF Converter.

public abstract class Pattern implements java.io.Serializable {
  public abstract <R,A> R accept(Pattern.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(bnfc.abs.Absyn.PLit p, A arg);
    public R visit(bnfc.abs.Absyn.PVar p, A arg);
    public R visit(bnfc.abs.Absyn.PSinglConstr p, A arg);
    public R visit(bnfc.abs.Absyn.PParamConstr p, A arg);
    public R visit(bnfc.abs.Absyn.PWildCard p, A arg);

  }

}
