package bnfc.abs.Absyn; // Java Package generated by the BNF Converter.

public class PParamConstr extends Pattern {
  public final QU qu_;
  public final ListPattern listpattern_;
  public PParamConstr(QU p1, ListPattern p2) { qu_ = p1; listpattern_ = p2; }

  public <R,A> R accept(bnfc.abs.Absyn.Pattern.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof bnfc.abs.Absyn.PParamConstr) {
      bnfc.abs.Absyn.PParamConstr x = (bnfc.abs.Absyn.PParamConstr)o;
      return this.qu_.equals(x.qu_) && this.listpattern_.equals(x.listpattern_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.qu_.hashCode())+this.listpattern_.hashCode();
  }


}
