package bnfc.abs.Absyn; // Java Package generated by the BNF Converter.

public class Prog extends Program {
  public final ListModule listmodule_;
  public Prog(ListModule p1) { listmodule_ = p1; }

  public <R,A> R accept(bnfc.abs.Absyn.Program.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof bnfc.abs.Absyn.Prog) {
      bnfc.abs.Absyn.Prog x = (bnfc.abs.Absyn.Prog)o;
      return this.listmodule_.equals(x.listmodule_);
    }
    return false;
  }

  public int hashCode() {
    return this.listmodule_.hashCode();
  }


}
