package bnfc.abs.Absyn; // Java Package generated by the BNF Converter.

public class PWildCard extends Pattern {
  public PWildCard() { }

  public <R,A> R accept(bnfc.abs.Absyn.Pattern.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof bnfc.abs.Absyn.PWildCard) {
      return true;
    }
    return false;
  }

  public int hashCode() {
    return 37;
  }


}
