package bnfc.abs.Absyn; // Java Package generated by the BNF Converter.

public abstract class QA implements java.io.Serializable {
  public abstract <R,A> R accept(QA.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(bnfc.abs.Absyn.LA p, A arg);
    public R visit(bnfc.abs.Absyn.UA p, A arg);
    public R visit(bnfc.abs.Absyn.QA_ p, A arg);

  }

}
