package bnfc.abs.Absyn; // Java Package generated by the BNF Converter.

public abstract class QL implements java.io.Serializable {
  public abstract <R,A> R accept(QL.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(bnfc.abs.Absyn.L_ p, A arg);
    public R visit(bnfc.abs.Absyn.QL_ p, A arg);

  }

}
