package bnfc.abs.Absyn; // Java Package generated by the BNF Converter.

public class QL_ extends QL {
  public final String u_;
  public final QL ql_;
  public QL_(String p1, QL p2) { u_ = p1; ql_ = p2; }

  public <R,A> R accept(bnfc.abs.Absyn.QL.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof bnfc.abs.Absyn.QL_) {
      bnfc.abs.Absyn.QL_ x = (bnfc.abs.Absyn.QL_)o;
      return this.u_.equals(x.u_) && this.ql_.equals(x.ql_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.u_.hashCode())+this.ql_.hashCode();
  }


}
