package bnfc.abs.Absyn; // Java Package generated by the BNF Converter.

public abstract class QU implements java.io.Serializable {
  public abstract <R,A> R accept(QU.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(bnfc.abs.Absyn.U_ p, A arg);
    public R visit(bnfc.abs.Absyn.QU_ p, A arg);

  }

}
