package bnfc.abs.Absyn; // Java Package generated by the BNF Converter.

public class QU_ extends QU {
  public final String u_;
  public final QU qu_;
  public QU_(String p1, QU p2) { u_ = p1; qu_ = p2; }

  public <R,A> R accept(bnfc.abs.Absyn.QU.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof bnfc.abs.Absyn.QU_) {
      bnfc.abs.Absyn.QU_ x = (bnfc.abs.Absyn.QU_)o;
      return this.u_.equals(x.u_) && this.qu_.equals(x.qu_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.u_.hashCode())+this.qu_.hashCode();
  }


}
