package bnfc.abs.Absyn; // Java Package generated by the BNF Converter.

public class RecordConstrType extends ConstrType {
  public final T t_;
  public final String l_;
  public RecordConstrType(T p1, String p2) { t_ = p1; l_ = p2; }

  public <R,A> R accept(bnfc.abs.Absyn.ConstrType.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof bnfc.abs.Absyn.RecordConstrType) {
      bnfc.abs.Absyn.RecordConstrType x = (bnfc.abs.Absyn.RecordConstrType)o;
      return this.t_.equals(x.t_) && this.l_.equals(x.l_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.t_.hashCode())+this.l_.hashCode();
  }


}
