package bnfc.abs.Absyn; // Java Package generated by the BNF Converter.

public class SAss extends Stm {
  public final String l_;
  public final Exp exp_;
  public SAss(String p1, Exp p2) { l_ = p1; exp_ = p2; }

  public <R,A> R accept(bnfc.abs.Absyn.Stm.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof bnfc.abs.Absyn.SAss) {
      bnfc.abs.Absyn.SAss x = (bnfc.abs.Absyn.SAss)o;
      return this.l_.equals(x.l_) && this.exp_.equals(x.exp_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.l_.hashCode())+this.exp_.hashCode();
  }


}
