package bnfc.abs.Absyn; // Java Package generated by the BNF Converter.

public class SAwait extends Stm {
  public final Guard guard_;
  public SAwait(Guard p1) { guard_ = p1; }

  public <R,A> R accept(bnfc.abs.Absyn.Stm.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof bnfc.abs.Absyn.SAwait) {
      bnfc.abs.Absyn.SAwait x = (bnfc.abs.Absyn.SAwait)o;
      return this.guard_.equals(x.guard_);
    }
    return false;
  }

  public int hashCode() {
    return this.guard_.hashCode();
  }


}
