package bnfc.abs.Absyn; // Java Package generated by the BNF Converter.

public class SCaseB extends SCaseBranch {
  public final Pattern pattern_;
  public final AnnStm annstm_;
  public SCaseB(Pattern p1, AnnStm p2) { pattern_ = p1; annstm_ = p2; }

  public <R,A> R accept(bnfc.abs.Absyn.SCaseBranch.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof bnfc.abs.Absyn.SCaseB) {
      bnfc.abs.Absyn.SCaseB x = (bnfc.abs.Absyn.SCaseB)o;
      return this.pattern_.equals(x.pattern_) && this.annstm_.equals(x.annstm_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.pattern_.hashCode())+this.annstm_.hashCode();
  }


}
