package bnfc.abs.Absyn; // Java Package generated by the BNF Converter.

public abstract class SCaseBranch implements java.io.Serializable {
  public abstract <R,A> R accept(SCaseBranch.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(bnfc.abs.Absyn.SCaseB p, A arg);

  }

}
