package bnfc.abs.Absyn; // Java Package generated by the BNF Converter.

public class SDecAss extends Stm {
  public final T t_;
  public final String l_;
  public final Exp exp_;
  public SDecAss(T p1, String p2, Exp p3) { t_ = p1; l_ = p2; exp_ = p3; }

  public <R,A> R accept(bnfc.abs.Absyn.Stm.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof bnfc.abs.Absyn.SDecAss) {
      bnfc.abs.Absyn.SDecAss x = (bnfc.abs.Absyn.SDecAss)o;
      return this.t_.equals(x.t_) && this.l_.equals(x.l_) && this.exp_.equals(x.exp_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(this.t_.hashCode())+this.l_.hashCode())+this.exp_.hashCode();
  }


}
