package bnfc.abs.Absyn; // Java Package generated by the BNF Converter.

public class SinglConstrIdent extends ConstrIdent {
  public final String u_;
  public SinglConstrIdent(String p1) { u_ = p1; }

  public <R,A> R accept(bnfc.abs.Absyn.ConstrIdent.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof bnfc.abs.Absyn.SinglConstrIdent) {
      bnfc.abs.Absyn.SinglConstrIdent x = (bnfc.abs.Absyn.SinglConstrIdent)o;
      return this.u_.equals(x.u_);
    }
    return false;
  }

  public int hashCode() {
    return this.u_.hashCode();
  }


}
