package bnfc.abs.Absyn; // Java Package generated by the BNF Converter.

public class Spawns extends EffExp {
  public final PureExp pureexp_;
  public final Type type_;
  public final ListPureExp listpureexp_;
  public Spawns(PureExp p1, Type p2, ListPureExp p3) { pureexp_ = p1; type_ = p2; listpureexp_ = p3; }

  public <R,A> R accept(bnfc.abs.Absyn.EffExp.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof bnfc.abs.Absyn.Spawns) {
      bnfc.abs.Absyn.Spawns x = (bnfc.abs.Absyn.Spawns)o;
      return this.pureexp_.equals(x.pureexp_) && this.type_.equals(x.type_) && this.listpureexp_.equals(x.listpureexp_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(this.pureexp_.hashCode())+this.type_.hashCode())+this.listpureexp_.hashCode();
  }


}
