package bnfc.abs.Absyn; // Java Package generated by the BNF Converter.

public class SPrintln extends Stm {
  public final PureExp pureexp_;
  public SPrintln(PureExp p1) { pureexp_ = p1; }

  public <R,A> R accept(bnfc.abs.Absyn.Stm.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof bnfc.abs.Absyn.SPrintln) {
      bnfc.abs.Absyn.SPrintln x = (bnfc.abs.Absyn.SPrintln)o;
      return this.pureexp_.equals(x.pureexp_);
    }
    return false;
  }

  public int hashCode() {
    return this.pureexp_.hashCode();
  }


}
