package bnfc.abs.Absyn; // Java Package generated by the BNF Converter.

public class StarFromImport extends Import {
  public final ImportType importtype_;
  public final QType qtype_;
  public StarFromImport(ImportType p1, QType p2) { importtype_ = p1; qtype_ = p2; }

  public <R,A> R accept(bnfc.abs.Absyn.Import.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof bnfc.abs.Absyn.StarFromImport) {
      bnfc.abs.Absyn.StarFromImport x = (bnfc.abs.Absyn.StarFromImport)o;
      return this.importtype_.equals(x.importtype_) && this.qtype_.equals(x.qtype_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.importtype_.hashCode())+this.qtype_.hashCode();
  }


}
