package bnfc.abs.Absyn; // Java Package generated by the BNF Converter.

public class StarFromImport extends Import {
  public final IsForeign isforeign_;
  public final QU qu_;
  public StarFromImport(IsForeign p1, QU p2) { isforeign_ = p1; qu_ = p2; }

  public <R,A> R accept(bnfc.abs.Absyn.Import.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof bnfc.abs.Absyn.StarFromImport) {
      bnfc.abs.Absyn.StarFromImport x = (bnfc.abs.Absyn.StarFromImport)o;
      return this.isforeign_.equals(x.isforeign_) && this.qu_.equals(x.qu_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.isforeign_.hashCode())+this.qu_.hashCode();
  }


}
