package bnfc.abs.Absyn; // Java Package generated by the BNF Converter.

public abstract class Stm implements java.io.Serializable {
  public abstract <R,A> R accept(Stm.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(bnfc.abs.Absyn.SSkip p, A arg);
    public R visit(bnfc.abs.Absyn.SSuspend p, A arg);
    public R visit(bnfc.abs.Absyn.SReturn p, A arg);
    public R visit(bnfc.abs.Absyn.SAssert p, A arg);
    public R visit(bnfc.abs.Absyn.SAwait p, A arg);
    public R visit(bnfc.abs.Absyn.SAss p, A arg);
    public R visit(bnfc.abs.Absyn.SFieldAss p, A arg);
    public R visit(bnfc.abs.Absyn.SDec p, A arg);
    public R visit(bnfc.abs.Absyn.SDecAss p, A arg);
    public R visit(bnfc.abs.Absyn.SWhile p, A arg);
    public R visit(bnfc.abs.Absyn.SIf p, A arg);
    public R visit(bnfc.abs.Absyn.SIfElse p, A arg);
    public R visit(bnfc.abs.Absyn.SCase p, A arg);
    public R visit(bnfc.abs.Absyn.SBlock p, A arg);
    public R visit(bnfc.abs.Absyn.SExp p, A arg);
    public R visit(bnfc.abs.Absyn.SPrint p, A arg);
    public R visit(bnfc.abs.Absyn.SPrintln p, A arg);
    public R visit(bnfc.abs.Absyn.SThrow p, A arg);
    public R visit(bnfc.abs.Absyn.STryCatchFinally p, A arg);
    public R visit(bnfc.abs.Absyn.SGive p, A arg);
    public R visit(bnfc.abs.Absyn.SDuration p, A arg);

  }

}
