package bnfc.abs.Absyn; // Java Package generated by the BNF Converter.

public class STryCatchFinally extends Stm {
  public final AnnStm annstm_;
  public final ListSCaseBranch listscasebranch_;
  public final MaybeFinally maybefinally_;
  public STryCatchFinally(AnnStm p1, ListSCaseBranch p2, MaybeFinally p3) { annstm_ = p1; listscasebranch_ = p2; maybefinally_ = p3; }

  public <R,A> R accept(bnfc.abs.Absyn.Stm.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof bnfc.abs.Absyn.STryCatchFinally) {
      bnfc.abs.Absyn.STryCatchFinally x = (bnfc.abs.Absyn.STryCatchFinally)o;
      return this.annstm_.equals(x.annstm_) && this.listscasebranch_.equals(x.listscasebranch_) && this.maybefinally_.equals(x.maybefinally_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(this.annstm_.hashCode())+this.listscasebranch_.hashCode())+this.maybefinally_.hashCode();
  }


}
