package bnfc.abs.Absyn; // Java Package generated by the BNF Converter.

public class STryCatchFinally extends Stm {
  public final Stm stm_;
  public final ListCatchBranch listcatchbranch_;
  public final MaybeFinally maybefinally_;
  public STryCatchFinally(Stm p1, ListCatchBranch p2, MaybeFinally p3) { stm_ = p1; listcatchbranch_ = p2; maybefinally_ = p3; }

  public <R,A> R accept(bnfc.abs.Absyn.Stm.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof bnfc.abs.Absyn.STryCatchFinally) {
      bnfc.abs.Absyn.STryCatchFinally x = (bnfc.abs.Absyn.STryCatchFinally)o;
      return this.stm_.equals(x.stm_) && this.listcatchbranch_.equals(x.listcatchbranch_) && this.maybefinally_.equals(x.maybefinally_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(this.stm_.hashCode())+this.listcatchbranch_.hashCode())+this.maybefinally_.hashCode();
  }


}
