package bnfc.abs.Absyn; // Java Package generated by the BNF Converter.

public class SWhile extends Stm {
  public final PureExp pureexp_;
  public final AnnStm annstm_;
  public SWhile(PureExp p1, AnnStm p2) { pureexp_ = p1; annstm_ = p2; }

  public <R,A> R accept(bnfc.abs.Absyn.Stm.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof bnfc.abs.Absyn.SWhile) {
      bnfc.abs.Absyn.SWhile x = (bnfc.abs.Absyn.SWhile)o;
      return this.pureexp_.equals(x.pureexp_) && this.annstm_.equals(x.annstm_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.pureexp_.hashCode())+this.annstm_.hashCode();
  }


}
