package bnfc.abs.Absyn; // Java Package generated by the BNF Converter.

public abstract class T implements java.io.Serializable {
  public abstract <R,A> R accept(T.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(bnfc.abs.Absyn.TSimple p, A arg);
    public R visit(bnfc.abs.Absyn.TPoly p, A arg);
    public R visit(bnfc.abs.Absyn.TInfer p, A arg);

  }

}
