package bnfc.abs.Absyn; // Java Package generated by the BNF Converter.

public class TGen extends Type {
  public final QType qtype_;
  public final ListType listtype_;
  public TGen(QType p1, ListType p2) { qtype_ = p1; listtype_ = p2; }

  public <R,A> R accept(bnfc.abs.Absyn.Type.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof bnfc.abs.Absyn.TGen) {
      bnfc.abs.Absyn.TGen x = (bnfc.abs.Absyn.TGen)o;
      return this.qtype_.equals(x.qtype_) && this.listtype_.equals(x.listtype_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.qtype_.hashCode())+this.listtype_.hashCode();
  }


}
