package bnfc.abs.Absyn; // Java Package generated by the BNF Converter.

public class ThisSyncMethCall extends EffExp {
  public final String l_;
  public final ListPureExp listpureexp_;
  public ThisSyncMethCall(String p1, ListPureExp p2) { l_ = p1; listpureexp_ = p2; }

  public <R,A> R accept(bnfc.abs.Absyn.EffExp.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof bnfc.abs.Absyn.ThisSyncMethCall) {
      bnfc.abs.Absyn.ThisSyncMethCall x = (bnfc.abs.Absyn.ThisSyncMethCall)o;
      return this.l_.equals(x.l_) && this.listpureexp_.equals(x.listpureexp_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.l_.hashCode())+this.listpureexp_.hashCode();
  }


}
