package bnfc.abs.Absyn; // Java Package generated by the BNF Converter.

public class TPoly extends T {
  public final QU qu_;
  public final ListT listt_;
  public TPoly(QU p1, ListT p2) { qu_ = p1; listt_ = p2; }

  public <R,A> R accept(bnfc.abs.Absyn.T.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof bnfc.abs.Absyn.TPoly) {
      bnfc.abs.Absyn.TPoly x = (bnfc.abs.Absyn.TPoly)o;
      return this.qu_.equals(x.qu_) && this.listt_.equals(x.listt_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.qu_.hashCode())+this.listt_.hashCode();
  }


}
