package bnfc.abs.Absyn; // Java Package generated by the BNF Converter.

public class TTyp extends TType {
  public final ListTTypeSegment listttypesegment_;
  public TTyp(ListTTypeSegment p1) { listttypesegment_ = p1; }

  public <R,A> R accept(bnfc.abs.Absyn.TType.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof bnfc.abs.Absyn.TTyp) {
      bnfc.abs.Absyn.TTyp x = (bnfc.abs.Absyn.TTyp)o;
      return this.listttypesegment_.equals(x.listttypesegment_);
    }
    return false;
  }

  public int hashCode() {
    return this.listttypesegment_.hashCode();
  }


}
