package bnfc.abs.Absyn; // Java Package generated by the BNF Converter.

public class TypeDecl extends Decl {
  public final String uident_;
  public final Type type_;
  public TypeDecl(String p1, Type p2) { uident_ = p1; type_ = p2; }

  public <R,A> R accept(bnfc.abs.Absyn.Decl.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof bnfc.abs.Absyn.TypeDecl) {
      bnfc.abs.Absyn.TypeDecl x = (bnfc.abs.Absyn.TypeDecl)o;
      return this.uident_.equals(x.uident_) && this.type_.equals(x.type_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.uident_.hashCode())+this.type_.hashCode();
  }


}
