package bnfc.abs.Absyn; // Java Package generated by the BNF Converter.

public class U_ extends QU {
  public final String u_;
  public U_(String p1) { u_ = p1; }

  public <R,A> R accept(bnfc.abs.Absyn.QU.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof bnfc.abs.Absyn.U_) {
      bnfc.abs.Absyn.U_ x = (bnfc.abs.Absyn.U_)o;
      return this.u_.equals(x.u_);
    }
    return false;
  }

  public int hashCode() {
    return this.u_.hashCode();
  }


}
