package bnfc.abs.Absyn; // Java Package generated by the BNF Converter.

public class VarGuard extends Guard {
  public final String lident_;
  public VarGuard(String p1) { lident_ = p1; }

  public <R,A> R accept(bnfc.abs.Absyn.Guard.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof bnfc.abs.Absyn.VarGuard) {
      bnfc.abs.Absyn.VarGuard x = (bnfc.abs.Absyn.VarGuard)o;
      return this.lident_.equals(x.lident_);
    }
    return false;
  }

  public int hashCode() {
    return this.lident_.hashCode();
  }


}
