/* The following code was generated by JFlex 1.6.1 */

// This JLex file was machine-generated by the BNF converter
package bnfc.abs;

import java_cup.runtime.*;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>src/main/java/bnfc/abs/Yylex</tt>
 */
public class Yylex implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int COMMENT = 2;
  public static final int CHAR = 4;
  public static final int CHARESC = 6;
  public static final int CHAREND = 8;
  public static final int STRING = 10;
  public static final int ESCAPED = 12;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2,  2,  2,  2,  2,  2,  3,  3,  4, 4
  };

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = {
     0,  0,  0,  0,  0,  0,  0,  0,  0, 56, 53,  0, 56, 56,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
    56, 19, 54,  0,  0, 23, 18,  0, 13, 14, 10, 20,  5, 21,  4, 22, 
     3,  3,  3,  3,  3,  3,  3,  3,  3,  3, 27,  9,  6, 11,  7, 17, 
     0,  1,  1, 52, 51,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 
     1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 25, 55, 26,  0,  8, 
     0, 28, 35, 39, 41, 30, 42, 48, 40, 34,  2, 50, 37, 46, 38, 43, 
    45,  2, 31, 29, 32, 36, 49, 33, 44, 47,  2, 15, 12, 16, 24,  0
  };

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\5\0\1\1\1\2\1\3\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\13\1\14\1\15\1\16\1\17"+
    "\1\20\1\21\1\22\1\23\1\24\1\25\1\26\1\27"+
    "\1\30\1\31\1\32\1\33\20\2\1\34\1\35\2\36"+
    "\1\37\1\40\1\41\1\42\1\43\1\44\1\45\1\46"+
    "\1\0\1\47\1\50\1\51\1\52\1\53\1\54\1\55"+
    "\1\56\1\0\13\2\1\57\1\60\21\2\1\61\1\62"+
    "\1\63\12\2\1\64\10\2\1\65\1\2\1\66\1\2"+
    "\1\67\4\2\1\70\7\2\1\71\1\0\3\2\1\72"+
    "\1\73\5\2\1\74\1\2\1\75\1\76\6\2\1\77"+
    "\1\100\2\2\1\101\1\2\1\102\5\2\1\62\1\0"+
    "\1\2\1\103\6\2\1\104\1\2\1\105\4\2\1\106"+
    "\1\107\1\110\3\2\1\111\4\2\1\112\3\2\1\113"+
    "\1\114\1\115\1\116\2\2\1\117\10\2\1\120\1\121"+
    "\1\122\3\2\1\123\1\2\1\124\1\125\1\126\1\127"+
    "\1\130\4\2\1\131\1\132\1\133\1\134\1\2\1\135";

  private static int [] zzUnpackAction() {
    int [] result = new int[243];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\71\0\162\0\253\0\344\0\u011d\0\u0156\0\u018f"+
    "\0\162\0\162\0\u01c8\0\u0201\0\162\0\162\0\162\0\u023a"+
    "\0\u0273\0\162\0\162\0\162\0\162\0\162\0\u02ac\0\u02e5"+
    "\0\162\0\162\0\u031e\0\162\0\162\0\162\0\162\0\162"+
    "\0\u0357\0\u0390\0\u03c9\0\u0402\0\u043b\0\u0474\0\u04ad\0\u04e6"+
    "\0\u051f\0\u0558\0\u0591\0\u05ca\0\u0603\0\u063c\0\u0675\0\u06ae"+
    "\0\162\0\162\0\162\0\u06e7\0\162\0\162\0\162\0\162"+
    "\0\162\0\162\0\162\0\162\0\u0720\0\162\0\162\0\162"+
    "\0\162\0\162\0\162\0\162\0\162\0\u0759\0\u0792\0\u07cb"+
    "\0\u0804\0\u083d\0\u0876\0\u08af\0\u08e8\0\u0921\0\u095a\0\u0993"+
    "\0\u09cc\0\u0a05\0\u0156\0\u0a3e\0\u0a77\0\u0ab0\0\u0ae9\0\u0b22"+
    "\0\u0b5b\0\u0b94\0\u0bcd\0\u0c06\0\u0c3f\0\u0c78\0\u0cb1\0\u0cea"+
    "\0\u0d23\0\u0d5c\0\u0d95\0\u0dce\0\162\0\u0e07\0\162\0\u0e40"+
    "\0\u0e79\0\u0eb2\0\u0eeb\0\u0f24\0\u0f5d\0\u0f96\0\u0fcf\0\u1008"+
    "\0\u1041\0\u0156\0\u107a\0\u10b3\0\u10ec\0\u1125\0\u115e\0\u1197"+
    "\0\u11d0\0\u1209\0\u0156\0\u1242\0\u0156\0\u127b\0\u0156\0\u12b4"+
    "\0\u12ed\0\u1326\0\u135f\0\u0156\0\u1398\0\u13d1\0\u140a\0\u1443"+
    "\0\u147c\0\u14b5\0\u14ee\0\u0156\0\u1527\0\u1560\0\u1599\0\u15d2"+
    "\0\u0156\0\u0156\0\u160b\0\u1644\0\u167d\0\u16b6\0\u16ef\0\u0156"+
    "\0\u1728\0\u1761\0\u0156\0\u179a\0\u17d3\0\u180c\0\u1845\0\u187e"+
    "\0\u18b7\0\u0156\0\u0156\0\u18f0\0\u1929\0\u0156\0\u1962\0\u0156"+
    "\0\u199b\0\u19d4\0\u1a0d\0\u1a46\0\u1a7f\0\u1ab8\0\u1ab8\0\u1af1"+
    "\0\u0156\0\u1b2a\0\u1b63\0\u1b9c\0\u1bd5\0\u1c0e\0\u1c47\0\u0156"+
    "\0\u1c80\0\u0156\0\u1cb9\0\u1cf2\0\u1d2b\0\u1d64\0\u0156\0\u0156"+
    "\0\u0156\0\u1d9d\0\u1dd6\0\u1e0f\0\u1e48\0\u1e81\0\u1eba\0\u1ef3"+
    "\0\u1f2c\0\u0156\0\u1f65\0\u1f9e\0\u1fd7\0\u0156\0\u0156\0\u0156"+
    "\0\u0156\0\u2010\0\u2049\0\u0156\0\u2082\0\u20bb\0\u20f4\0\u212d"+
    "\0\u2166\0\u219f\0\u21d8\0\u2211\0\u0156\0\u0156\0\u0156\0\u224a"+
    "\0\u2283\0\u22bc\0\u0156\0\u22f5\0\u0156\0\u0156\0\u0156\0\u0156"+
    "\0\u0156\0\u232e\0\u2367\0\u23a0\0\u23d9\0\u0156\0\u0156\0\u0156"+
    "\0\u0156\0\u2412\0\u0156";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[243];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\0\1\6\1\7\1\10\1\11\1\12\1\13\1\14"+
    "\1\15\1\16\1\17\1\20\1\21\1\22\1\23\1\24"+
    "\1\25\1\26\1\27\1\30\1\31\1\32\1\33\1\34"+
    "\1\35\1\36\1\37\1\40\1\41\1\42\1\43\1\44"+
    "\1\45\1\46\1\47\1\50\1\7\1\51\1\52\1\53"+
    "\1\7\1\54\1\55\2\7\1\56\1\57\1\7\1\60"+
    "\2\7\2\6\1\61\1\62\1\0\1\61\12\63\1\64"+
    "\56\63\71\0\65\65\1\0\1\66\1\67\1\65\40\70"+
    "\1\71\5\70\1\72\16\70\1\0\1\73\1\74\1\70"+
    "\1\0\3\6\4\0\1\6\23\0\31\6\5\0\3\7"+
    "\4\0\1\7\23\0\31\7\7\0\1\10\1\75\77\0"+
    "\1\76\70\0\1\77\64\0\1\100\3\0\1\101\71\0"+
    "\1\102\76\0\1\103\61\0\1\104\67\0\1\105\13\0"+
    "\1\106\43\0\3\7\4\0\1\7\23\0\1\7\1\107"+
    "\3\7\1\110\23\7\5\0\3\7\4\0\1\7\23\0"+
    "\10\7\1\111\15\7\1\112\2\7\5\0\3\7\4\0"+
    "\1\7\23\0\11\7\1\113\6\7\1\114\10\7\5\0"+
    "\3\7\4\0\1\7\23\0\2\7\1\115\26\7\5\0"+
    "\3\7\4\0\1\7\23\0\3\7\1\116\10\7\1\117"+
    "\6\7\1\120\5\7\5\0\3\7\4\0\1\7\23\0"+
    "\14\7\1\121\14\7\5\0\3\7\4\0\1\7\23\0"+
    "\12\7\1\122\3\7\1\123\3\7\1\124\6\7\5\0"+
    "\3\7\4\0\1\7\23\0\10\7\1\125\20\7\5\0"+
    "\3\7\4\0\1\7\23\0\2\7\1\126\14\7\1\127"+
    "\11\7\5\0\3\7\4\0\1\7\23\0\2\7\1\130"+
    "\5\7\1\131\6\7\1\132\11\7\5\0\3\7\4\0"+
    "\1\7\23\0\1\133\10\7\1\134\17\7\5\0\3\7"+
    "\4\0\1\7\23\0\1\135\1\7\1\136\5\7\1\137"+
    "\20\7\5\0\3\7\4\0\1\7\23\0\3\7\1\140"+
    "\2\7\1\141\22\7\5\0\3\7\4\0\1\7\23\0"+
    "\3\7\1\142\25\7\5\0\3\7\4\0\1\7\23\0"+
    "\17\7\1\143\11\7\5\0\3\7\4\0\1\7\23\0"+
    "\2\7\1\144\26\7\32\0\1\145\45\0\1\146\65\0"+
    "\65\106\1\147\3\106\1\0\3\7\4\0\1\7\23\0"+
    "\1\7\1\150\27\7\5\0\3\7\4\0\1\7\23\0"+
    "\1\151\30\7\5\0\3\7\4\0\1\7\23\0\1\7"+
    "\1\152\27\7\5\0\3\7\4\0\1\7\23\0\6\7"+
    "\1\153\22\7\5\0\3\7\4\0\1\7\23\0\1\7"+
    "\1\154\27\7\5\0\3\7\4\0\1\7\23\0\4\7"+
    "\1\155\6\7\1\156\5\7\1\157\7\7\5\0\3\7"+
    "\4\0\1\7\23\0\1\160\3\7\1\161\24\7\5\0"+
    "\3\7\4\0\1\7\23\0\23\7\1\162\5\7\5\0"+
    "\3\7\4\0\1\7\23\0\2\7\1\163\1\164\2\7"+
    "\1\165\22\7\5\0\3\7\4\0\1\7\23\0\21\7"+
    "\1\166\7\7\5\0\3\7\4\0\1\7\23\0\6\7"+
    "\1\167\22\7\5\0\3\7\4\0\1\7\23\0\4\7"+
    "\1\170\24\7\5\0\3\7\4\0\1\7\23\0\21\7"+
    "\1\171\7\7\5\0\3\7\4\0\1\7\23\0\6\7"+
    "\1\172\22\7\5\0\3\7\4\0\1\7\23\0\4\7"+
    "\1\173\24\7\5\0\3\7\4\0\1\7\23\0\13\7"+
    "\1\174\15\7\5\0\3\7\4\0\1\7\23\0\5\7"+
    "\1\175\23\7\5\0\3\7\4\0\1\7\23\0\11\7"+
    "\1\176\17\7\5\0\3\7\4\0\1\7\23\0\5\7"+
    "\1\177\23\7\5\0\3\7\4\0\1\7\23\0\1\7"+
    "\1\200\2\7\1\201\24\7\5\0\3\7\4\0\1\7"+
    "\23\0\1\202\30\7\5\0\3\7\4\0\1\7\23\0"+
    "\4\7\1\203\24\7\5\0\3\7\4\0\1\7\23\0"+
    "\16\7\1\204\12\7\5\0\3\7\4\0\1\7\23\0"+
    "\3\7\1\205\25\7\5\0\3\7\4\0\1\7\23\0"+
    "\17\7\1\206\11\7\5\0\3\7\4\0\1\7\23\0"+
    "\12\7\1\207\7\7\1\210\6\7\5\0\3\7\4\0"+
    "\1\7\23\0\6\7\1\211\10\7\1\212\11\7\5\0"+
    "\3\7\4\0\1\7\23\0\15\7\1\213\13\7\5\0"+
    "\3\7\4\0\1\7\23\0\4\7\1\214\24\7\7\0"+
    "\1\146\32\0\1\215\33\0\3\7\4\0\1\7\23\0"+
    "\2\7\1\216\26\7\5\0\3\7\4\0\1\7\23\0"+
    "\6\7\1\217\22\7\5\0\3\7\4\0\1\7\23\0"+
    "\21\7\1\220\7\7\5\0\3\7\4\0\1\7\23\0"+
    "\21\7\1\221\7\7\5\0\3\7\4\0\1\7\23\0"+
    "\2\7\1\222\26\7\5\0\3\7\4\0\1\7\23\0"+
    "\2\7\1\223\26\7\5\0\3\7\4\0\1\7\23\0"+
    "\2\7\1\224\26\7\5\0\3\7\4\0\1\7\23\0"+
    "\17\7\1\225\11\7\5\0\3\7\4\0\1\7\23\0"+
    "\15\7\1\226\13\7\5\0\3\7\4\0\1\7\23\0"+
    "\10\7\1\227\20\7\5\0\3\7\4\0\1\7\23\0"+
    "\12\7\1\230\16\7\5\0\3\7\4\0\1\7\23\0"+
    "\17\7\1\231\11\7\5\0\3\7\4\0\1\7\23\0"+
    "\1\7\1\232\27\7\5\0\3\7\4\0\1\7\23\0"+
    "\2\7\1\233\26\7\5\0\3\7\4\0\1\7\23\0"+
    "\11\7\1\234\17\7\5\0\3\7\4\0\1\7\23\0"+
    "\2\7\1\235\26\7\5\0\3\7\4\0\1\7\23\0"+
    "\11\7\1\236\5\7\1\237\11\7\5\0\3\7\4\0"+
    "\1\7\23\0\11\7\1\240\17\7\5\0\3\7\4\0"+
    "\1\7\23\0\1\241\30\7\5\0\3\7\4\0\1\7"+
    "\23\0\11\7\1\242\17\7\5\0\3\7\4\0\1\7"+
    "\23\0\2\7\1\243\26\7\5\0\3\7\4\0\1\7"+
    "\23\0\13\7\1\244\15\7\5\0\3\7\4\0\1\7"+
    "\23\0\1\7\1\245\27\7\5\0\3\7\4\0\1\7"+
    "\23\0\1\246\30\7\5\0\3\7\4\0\1\7\23\0"+
    "\1\247\30\7\5\0\3\7\4\0\1\7\23\0\22\7"+
    "\1\250\6\7\5\0\3\7\4\0\1\7\23\0\1\251"+
    "\30\7\5\0\3\7\4\0\1\7\23\0\21\7\1\252"+
    "\7\7\5\0\3\7\4\0\1\7\23\0\12\7\1\253"+
    "\16\7\5\0\3\7\4\0\1\254\23\0\31\7\5\0"+
    "\3\7\4\0\1\7\23\0\10\7\1\255\20\7\7\0"+
    "\1\256\21\0\1\257\44\0\3\7\4\0\1\7\23\0"+
    "\3\7\1\260\25\7\5\0\3\7\4\0\1\7\23\0"+
    "\4\7\1\261\24\7\5\0\3\7\4\0\1\7\23\0"+
    "\2\7\1\262\26\7\5\0\3\7\4\0\1\7\23\0"+
    "\12\7\1\263\16\7\5\0\3\7\4\0\1\7\23\0"+
    "\21\7\1\264\7\7\5\0\3\7\4\0\1\7\23\0"+
    "\3\7\1\265\25\7\5\0\3\7\4\0\1\7\23\0"+
    "\11\7\1\266\17\7\5\0\3\7\4\0\1\7\23\0"+
    "\3\7\1\267\25\7\5\0\3\7\4\0\1\7\23\0"+
    "\5\7\1\270\23\7\5\0\3\7\4\0\1\7\23\0"+
    "\27\7\1\271\1\7\5\0\3\7\4\0\1\7\23\0"+
    "\2\7\1\272\26\7\5\0\3\7\4\0\1\7\23\0"+
    "\3\7\1\273\25\7\5\0\3\7\4\0\1\7\23\0"+
    "\2\7\1\274\26\7\5\0\3\7\4\0\1\7\23\0"+
    "\3\7\1\275\25\7\5\0\3\7\4\0\1\7\23\0"+
    "\4\7\1\276\24\7\5\0\3\7\4\0\1\7\23\0"+
    "\11\7\1\277\17\7\5\0\3\7\4\0\1\7\23\0"+
    "\14\7\1\300\14\7\5\0\3\7\4\0\1\7\23\0"+
    "\1\7\1\301\27\7\5\0\3\7\4\0\1\7\23\0"+
    "\4\7\1\302\24\7\5\0\3\7\4\0\1\7\23\0"+
    "\11\7\1\303\17\7\5\0\3\7\4\0\1\7\23\0"+
    "\17\7\1\304\11\7\5\0\3\7\4\0\1\7\23\0"+
    "\4\7\1\305\24\7\5\0\3\7\4\0\1\7\23\0"+
    "\4\7\1\306\5\7\1\307\11\7\1\310\4\7\5\0"+
    "\3\7\4\0\1\7\23\0\11\7\1\311\17\7\7\0"+
    "\1\256\66\0\3\7\4\0\1\7\23\0\4\7\1\312"+
    "\24\7\5\0\3\7\4\0\1\7\23\0\12\7\1\313"+
    "\16\7\5\0\3\7\4\0\1\7\23\0\15\7\1\314"+
    "\13\7\5\0\3\7\4\0\1\7\23\0\4\7\1\315"+
    "\24\7\5\0\3\7\4\0\1\7\23\0\4\7\1\316"+
    "\24\7\5\0\3\7\4\0\1\7\23\0\12\7\1\317"+
    "\16\7\5\0\3\7\4\0\1\7\23\0\12\7\1\320"+
    "\16\7\5\0\3\7\4\0\1\7\23\0\30\7\1\321"+
    "\5\0\3\7\4\0\1\7\23\0\16\7\1\322\12\7"+
    "\5\0\3\7\4\0\1\7\23\0\22\7\1\323\6\7"+
    "\5\0\3\7\4\0\1\7\23\0\4\7\1\324\24\7"+
    "\5\0\3\7\4\0\1\7\23\0\6\7\1\325\22\7"+
    "\5\0\3\7\4\0\1\7\23\0\6\7\1\326\22\7"+
    "\5\0\3\7\4\0\1\7\23\0\11\7\1\327\17\7"+
    "\5\0\3\7\4\0\1\7\23\0\3\7\1\330\25\7"+
    "\5\0\3\7\4\0\1\7\23\0\11\7\1\331\17\7"+
    "\5\0\3\7\4\0\1\7\23\0\3\7\1\332\25\7"+
    "\5\0\3\7\4\0\1\7\23\0\2\7\1\333\26\7"+
    "\5\0\3\7\4\0\1\7\23\0\6\7\1\334\22\7"+
    "\5\0\3\7\4\0\1\7\23\0\2\7\1\335\26\7"+
    "\5\0\3\7\4\0\1\7\23\0\15\7\1\336\13\7"+
    "\5\0\3\7\4\0\1\7\23\0\1\7\1\337\27\7"+
    "\5\0\3\7\4\0\1\7\23\0\6\7\1\340\22\7"+
    "\5\0\3\7\4\0\1\7\23\0\1\341\30\7\5\0"+
    "\3\7\4\0\1\7\23\0\2\7\1\342\26\7\5\0"+
    "\3\7\4\0\1\7\23\0\12\7\1\343\16\7\5\0"+
    "\3\7\4\0\1\7\23\0\17\7\1\344\11\7\5\0"+
    "\3\7\4\0\1\7\23\0\23\7\1\345\5\7\5\0"+
    "\3\7\4\0\1\7\23\0\4\7\1\346\24\7\5\0"+
    "\3\7\4\0\1\7\23\0\12\7\1\347\16\7\5\0"+
    "\3\7\4\0\1\7\23\0\23\7\1\350\5\7\5\0"+
    "\3\7\4\0\1\7\23\0\5\7\1\351\23\7\5\0"+
    "\3\7\4\0\1\7\23\0\25\7\1\352\3\7\5\0"+
    "\3\7\4\0\1\7\23\0\17\7\1\353\11\7\5\0"+
    "\3\7\4\0\1\7\23\0\13\7\1\354\15\7\5\0"+
    "\3\7\4\0\1\7\23\0\12\7\1\355\16\7\5\0"+
    "\3\7\4\0\1\7\23\0\12\7\1\356\16\7\5\0"+
    "\3\7\4\0\1\7\23\0\2\7\1\357\26\7\5\0"+
    "\3\7\4\0\1\7\23\0\12\7\1\360\16\7\5\0"+
    "\3\7\4\0\1\7\23\0\2\7\1\361\26\7\5\0"+
    "\3\7\4\0\1\7\23\0\4\7\1\362\24\7\5\0"+
    "\3\7\4\0\1\7\23\0\1\7\1\363\27\7\4\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[9291];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\1\10\2\0\3\1\2\11\2\1\3\11\2\1"+
    "\5\11\2\1\2\11\1\1\5\11\20\1\3\11\1\1"+
    "\10\11\1\0\10\11\1\0\36\1\1\11\1\1\1\11"+
    "\45\1\1\0\41\1\1\0\104\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[243];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
  String pstring = new String();
  public int line_num() { return (yyline+1); }
  public String buff() {return new String(zzBuffer,zzCurrentPos,10).trim();}


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Yylex(java.io.Reader in) {
    this.zzReader = in;
  }



  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          zzR = false;
          break;
        case '\r':
          yyline++;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
          }
          break;
        default:
          zzR = false;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { return new Symbol(sym.U, yytext().intern());
            }
          case 94: break;
          case 2: 
            { return new Symbol(sym.L, yytext().intern());
            }
          case 95: break;
          case 3: 
            { return new Symbol(sym._INTEGER_, new Long(yytext()));
            }
          case 96: break;
          case 4: 
            { return new Symbol(sym._SYMB_0);
            }
          case 97: break;
          case 5: 
            { return new Symbol(sym._SYMB_1);
            }
          case 98: break;
          case 6: 
            { return new Symbol(sym._SYMB_2);
            }
          case 99: break;
          case 7: 
            { return new Symbol(sym._SYMB_3);
            }
          case 100: break;
          case 8: 
            { return new Symbol(sym._SYMB_4);
            }
          case 101: break;
          case 9: 
            { return new Symbol(sym._SYMB_5);
            }
          case 102: break;
          case 10: 
            { return new Symbol(sym._SYMB_6);
            }
          case 103: break;
          case 11: 
            { return new Symbol(sym._SYMB_7);
            }
          case 104: break;
          case 12: 
            { return new Symbol(sym._SYMB_8);
            }
          case 105: break;
          case 13: 
            { return new Symbol(sym._SYMB_9);
            }
          case 106: break;
          case 14: 
            { return new Symbol(sym._SYMB_10);
            }
          case 107: break;
          case 15: 
            { return new Symbol(sym._SYMB_11);
            }
          case 108: break;
          case 16: 
            { return new Symbol(sym._SYMB_12);
            }
          case 109: break;
          case 17: 
            { return new Symbol(sym._SYMB_14);
            }
          case 110: break;
          case 18: 
            { return new Symbol(sym._SYMB_15);
            }
          case 111: break;
          case 19: 
            { return new Symbol(sym._SYMB_29);
            }
          case 112: break;
          case 20: 
            { return new Symbol(sym._SYMB_22);
            }
          case 113: break;
          case 21: 
            { return new Symbol(sym._SYMB_23);
            }
          case 114: break;
          case 22: 
            { return new Symbol(sym._SYMB_24);
            }
          case 115: break;
          case 23: 
            { return new Symbol(sym._SYMB_25);
            }
          case 116: break;
          case 24: 
            { return new Symbol(sym._SYMB_26);
            }
          case 117: break;
          case 25: 
            { return new Symbol(sym._SYMB_27);
            }
          case 118: break;
          case 26: 
            { return new Symbol(sym._SYMB_28);
            }
          case 119: break;
          case 27: 
            { return new Symbol(sym._SYMB_30);
            }
          case 120: break;
          case 28: 
            { /* ignore white space. */
            }
          case 121: break;
          case 29: 
            { yybegin(STRING);
            }
          case 122: break;
          case 30: 
            { 
            }
          case 123: break;
          case 31: 
            { pstring += yytext();
            }
          case 124: break;
          case 32: 
            { String foo = pstring; pstring = new String(); yybegin(YYINITIAL); return new Symbol(sym._STRING_, foo.intern());
            }
          case 125: break;
          case 33: 
            { yybegin(ESCAPED);
            }
          case 126: break;
          case 34: 
            { pstring += yytext(); yybegin(STRING);
            }
          case 127: break;
          case 35: 
            { pstring += "\t"; yybegin(STRING);
            }
          case 128: break;
          case 36: 
            { pstring +=  "\n"; yybegin(STRING);
            }
          case 129: break;
          case 37: 
            { pstring += "\""; yybegin(STRING);
            }
          case 130: break;
          case 38: 
            { pstring += "\\"; yybegin(STRING);
            }
          case 131: break;
          case 39: 
            { return new Symbol(sym._SYMB_20);
            }
          case 132: break;
          case 40: 
            { return new Symbol(sym._SYMB_21);
            }
          case 133: break;
          case 41: 
            { return new Symbol(sym._SYMB_13);
            }
          case 134: break;
          case 42: 
            { return new Symbol(sym._SYMB_18);
            }
          case 135: break;
          case 43: 
            { return new Symbol(sym._SYMB_16);
            }
          case 136: break;
          case 44: 
            { return new Symbol(sym._SYMB_17);
            }
          case 137: break;
          case 45: 
            { return new Symbol(sym._SYMB_19);
            }
          case 138: break;
          case 46: 
            { yybegin(COMMENT);
            }
          case 139: break;
          case 47: 
            { return new Symbol(sym._SYMB_51);
            }
          case 140: break;
          case 48: 
            { return new Symbol(sym._SYMB_48);
            }
          case 141: break;
          case 49: 
            { yybegin(YYINITIAL);
            }
          case 142: break;
          case 50: 
            { return new Symbol(sym._DOUBLE_, new Double(yytext()));
            }
          case 143: break;
          case 51: 
            { /* BNFC single-line comment */
            }
          case 144: break;
          case 52: 
            { return new Symbol(sym._SYMB_72);
            }
          case 145: break;
          case 53: 
            { return new Symbol(sym._SYMB_53);
            }
          case 146: break;
          case 54: 
            { return new Symbol(sym._SYMB_56);
            }
          case 147: break;
          case 55: 
            { return new Symbol(sym._SYMB_57);
            }
          case 148: break;
          case 56: 
            { return new Symbol(sym._SYMB_38);
            }
          case 149: break;
          case 57: 
            { return new Symbol(sym._SYMB_47);
            }
          case 150: break;
          case 58: 
            { return new Symbol(sym._SYMB_66);
            }
          case 151: break;
          case 59: 
            { return new Symbol(sym._SYMB_40);
            }
          case 152: break;
          case 60: 
            { return new Symbol(sym._SYMB_68);
            }
          case 153: break;
          case 61: 
            { return new Symbol(sym._SYMB_69);
            }
          case 154: break;
          case 62: 
            { return new Symbol(sym._SYMB_73);
            }
          case 155: break;
          case 63: 
            { return new Symbol(sym._SYMB_58);
            }
          case 156: break;
          case 64: 
            { return new Symbol(sym._SYMB_34);
            }
          case 157: break;
          case 65: 
            { return new Symbol(sym._SYMB_37);
            }
          case 158: break;
          case 66: 
            { return new Symbol(sym._SYMB_46);
            }
          case 159: break;
          case 67: 
            { return new Symbol(sym._SYMB_32);
            }
          case 160: break;
          case 68: 
            { return new Symbol(sym._SYMB_71);
            }
          case 161: break;
          case 69: 
            { return new Symbol(sym._SYMB_74);
            }
          case 162: break;
          case 70: 
            { return new Symbol(sym._SYMB_54);
            }
          case 163: break;
          case 71: 
            { return new Symbol(sym._SYMB_35);
            }
          case 164: break;
          case 72: 
            { return new Symbol(sym._SYMB_36);
            }
          case 165: break;
          case 73: 
            { return new Symbol(sym._SYMB_59);
            }
          case 166: break;
          case 74: 
            { return new Symbol(sym._SYMB_31);
            }
          case 167: break;
          case 75: 
            { return new Symbol(sym._SYMB_42);
            }
          case 168: break;
          case 76: 
            { return new Symbol(sym._SYMB_64);
            }
          case 169: break;
          case 77: 
            { return new Symbol(sym._SYMB_65);
            }
          case 170: break;
          case 78: 
            { return new Symbol(sym._SYMB_70);
            }
          case 171: break;
          case 79: 
            { return new Symbol(sym._SYMB_50);
            }
          case 172: break;
          case 80: 
            { return new Symbol(sym._SYMB_55);
            }
          case 173: break;
          case 81: 
            { return new Symbol(sym._SYMB_67);
            }
          case 174: break;
          case 82: 
            { return new Symbol(sym._SYMB_43);
            }
          case 175: break;
          case 83: 
            { return new Symbol(sym._SYMB_33);
            }
          case 176: break;
          case 84: 
            { return new Symbol(sym._SYMB_45);
            }
          case 177: break;
          case 85: 
            { return new Symbol(sym._SYMB_44);
            }
          case 178: break;
          case 86: 
            { return new Symbol(sym._SYMB_60);
            }
          case 179: break;
          case 87: 
            { return new Symbol(sym._SYMB_63);
            }
          case 180: break;
          case 88: 
            { return new Symbol(sym._SYMB_62);
            }
          case 181: break;
          case 89: 
            { return new Symbol(sym._SYMB_39);
            }
          case 182: break;
          case 90: 
            { return new Symbol(sym._SYMB_61);
            }
          case 183: break;
          case 91: 
            { return new Symbol(sym._SYMB_41);
            }
          case 184: break;
          case 92: 
            { return new Symbol(sym._SYMB_52);
            }
          case 185: break;
          case 93: 
            { return new Symbol(sym._SYMB_49);
            }
          case 186: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
