/* The following code was generated by JFlex 1.6.1 */

// This JLex file was machine-generated by the BNF converter
package bnfc.abs;

import java_cup.runtime.*;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>src/main/java/bnfc/abs/Yylex</tt>
 */
public class Yylex implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int COMMENT = 2;
  public static final int CHAR = 4;
  public static final int CHARESC = 6;
  public static final int CHAREND = 8;
  public static final int STRING = 10;
  public static final int ESCAPED = 12;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2,  2,  2,  2,  2,  2,  3,  3,  4, 4
  };

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = {
     0,  0,  0,  0,  0,  0,  0,  0,  0, 55, 52,  0, 55, 55,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
    55, 20, 53,  0,  0, 24, 19,  4, 13, 14,  7, 21,  5, 22, 11, 23, 
     3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  0,  6,  9, 12, 10, 18, 
     0,  1,  1, 51, 50,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 
     1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 26, 54, 27,  0,  8, 
     0, 28, 35, 39, 41, 30, 42, 48, 40, 34,  2, 49, 37, 46, 38, 45, 
    44,  2, 31, 29, 32, 36,  2, 33, 43, 47,  2, 16, 15, 17, 25,  0
  };

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\5\0\1\1\1\2\1\3\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\13\1\14\1\15\1\16\1\17"+
    "\1\20\1\21\1\22\1\23\1\24\1\25\1\26\1\27"+
    "\1\30\1\31\1\32\20\2\1\33\1\34\2\35\1\36"+
    "\1\37\1\40\1\41\1\42\1\43\1\44\1\45\1\46"+
    "\1\47\1\50\1\51\1\52\1\53\1\54\1\55\1\0"+
    "\14\2\1\56\1\57\17\2\1\60\1\61\12\2\1\62"+
    "\10\2\1\63\1\2\1\64\5\2\1\65\5\2\1\66"+
    "\4\2\1\67\1\70\4\2\1\71\1\2\1\72\1\73"+
    "\6\2\1\74\1\75\2\2\1\76\1\77\5\2\1\100"+
    "\6\2\1\101\1\2\1\102\4\2\1\103\1\104\1\105"+
    "\4\2\1\106\1\2\1\107\2\2\1\110\1\111\1\112"+
    "\2\2\1\113\4\2\1\114\1\115\1\116\3\2\1\117"+
    "\1\120\1\121\1\122\3\2\1\123\1\124\1\2\1\125";

  private static int [] zzUnpackAction() {
    int [] result = new int[217];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\70\0\160\0\250\0\340\0\u0118\0\u0150\0\u0188"+
    "\0\160\0\160\0\160\0\160\0\u01c0\0\u01f8\0\160\0\u0230"+
    "\0\160\0\160\0\u0268\0\160\0\160\0\160\0\u02a0\0\u02d8"+
    "\0\160\0\160\0\u0310\0\160\0\160\0\160\0\160\0\u0348"+
    "\0\u0380\0\u03b8\0\u03f0\0\u0428\0\u0460\0\u0498\0\u04d0\0\u0508"+
    "\0\u0540\0\u0578\0\u05b0\0\u05e8\0\u0620\0\u0658\0\u0690\0\160"+
    "\0\160\0\160\0\u06c8\0\160\0\160\0\160\0\160\0\160"+
    "\0\160\0\160\0\160\0\160\0\160\0\160\0\160\0\160"+
    "\0\160\0\160\0\160\0\u0700\0\u0738\0\u0770\0\u07a8\0\u07e0"+
    "\0\u0818\0\u0850\0\u0888\0\u08c0\0\u08f8\0\u0930\0\u0968\0\u09a0"+
    "\0\u09d8\0\u0150\0\u0a10\0\u0a48\0\u0a80\0\u0ab8\0\u0af0\0\u0b28"+
    "\0\u0b60\0\u0b98\0\u0bd0\0\u0c08\0\u0c40\0\u0c78\0\u0cb0\0\u0ce8"+
    "\0\u0d20\0\160\0\160\0\u0d58\0\u0d90\0\u0dc8\0\u0e00\0\u0e38"+
    "\0\u0e70\0\u0ea8\0\u0ee0\0\u0f18\0\u0f50\0\u0150\0\u0f88\0\u0fc0"+
    "\0\u0ff8\0\u1030\0\u1068\0\u10a0\0\u10d8\0\u1110\0\u0150\0\u1148"+
    "\0\u0150\0\u1180\0\u11b8\0\u11f0\0\u1228\0\u1260\0\u0150\0\u1298"+
    "\0\u12d0\0\u1308\0\u1340\0\u1378\0\u0150\0\u13b0\0\u13e8\0\u1420"+
    "\0\u1458\0\u0150\0\u0150\0\u1490\0\u14c8\0\u1500\0\u1538\0\u0150"+
    "\0\u1570\0\u15a8\0\u0150\0\u15e0\0\u1618\0\u1650\0\u1688\0\u16c0"+
    "\0\u16f8\0\u0150\0\u0150\0\u1730\0\u1768\0\u0150\0\u0150\0\u17a0"+
    "\0\u17d8\0\u1810\0\u1848\0\u1880\0\u0150\0\u18b8\0\u18f0\0\u1928"+
    "\0\u1960\0\u1998\0\u19d0\0\u0150\0\u1a08\0\u0150\0\u1a40\0\u1a78"+
    "\0\u1ab0\0\u1ae8\0\u0150\0\u0150\0\u0150\0\u1b20\0\u1b58\0\u1b90"+
    "\0\u1bc8\0\u0150\0\u1c00\0\u0150\0\u1c38\0\u1c70\0\u0150\0\u0150"+
    "\0\u0150\0\u1ca8\0\u1ce0\0\u0150\0\u1d18\0\u1d50\0\u1d88\0\u1dc0"+
    "\0\u0150\0\u0150\0\u0150\0\u1df8\0\u1e30\0\u1e68\0\u0150\0\u0150"+
    "\0\u0150\0\u0150\0\u1ea0\0\u1ed8\0\u1f10\0\u0150\0\u0150\0\u1f48"+
    "\0\u0150";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[217];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\0\1\6\1\7\1\10\1\0\1\11\1\12\1\13"+
    "\1\14\1\15\1\16\1\17\1\20\1\21\1\22\1\23"+
    "\1\24\1\25\1\26\1\27\1\30\1\31\1\32\1\33"+
    "\1\34\1\35\1\36\1\37\1\40\1\41\1\42\1\43"+
    "\1\44\1\45\1\46\1\47\1\7\1\50\1\51\1\52"+
    "\1\7\1\53\1\54\1\7\1\55\1\7\1\56\1\7"+
    "\1\57\1\7\2\6\1\60\1\61\1\0\1\60\7\62"+
    "\1\63\60\62\70\0\64\64\1\0\1\65\1\66\1\64"+
    "\40\67\1\70\5\67\1\71\15\67\1\0\1\72\1\73"+
    "\1\67\1\0\4\6\3\0\1\6\23\0\30\6\5\0"+
    "\4\7\3\0\1\7\23\0\30\7\7\0\1\10\100\0"+
    "\1\74\67\0\1\75\65\0\1\76\1\0\1\77\72\0"+
    "\1\100\73\0\1\101\60\0\1\102\62\0\1\103\17\0"+
    "\1\104\41\0\4\7\3\0\1\7\23\0\1\7\1\105"+
    "\3\7\1\106\22\7\5\0\4\7\3\0\1\7\23\0"+
    "\10\7\1\107\7\7\1\110\4\7\1\111\2\7\5\0"+
    "\4\7\3\0\1\7\23\0\11\7\1\112\5\7\1\113"+
    "\10\7\5\0\4\7\3\0\1\7\23\0\2\7\1\114"+
    "\25\7\5\0\4\7\3\0\1\7\23\0\3\7\1\115"+
    "\10\7\1\116\6\7\1\117\4\7\5\0\4\7\3\0"+
    "\1\7\23\0\14\7\1\120\13\7\5\0\4\7\3\0"+
    "\1\7\23\0\12\7\1\121\3\7\1\122\3\7\1\123"+
    "\5\7\5\0\4\7\3\0\1\7\23\0\10\7\1\124"+
    "\17\7\5\0\4\7\3\0\1\7\23\0\2\7\1\125"+
    "\16\7\1\126\6\7\5\0\4\7\3\0\1\7\23\0"+
    "\2\7\1\127\5\7\1\130\17\7\5\0\4\7\3\0"+
    "\1\7\23\0\1\131\10\7\1\132\16\7\5\0\4\7"+
    "\3\0\1\7\23\0\1\133\1\7\1\134\25\7\5\0"+
    "\4\7\3\0\1\7\23\0\3\7\1\135\2\7\1\136"+
    "\21\7\5\0\4\7\3\0\1\7\23\0\3\7\1\137"+
    "\24\7\5\0\4\7\3\0\1\7\23\0\21\7\1\140"+
    "\6\7\5\0\4\7\3\0\1\7\23\0\2\7\1\141"+
    "\25\7\33\0\1\142\40\0\64\104\1\143\3\104\1\0"+
    "\4\7\3\0\1\7\23\0\1\7\1\144\26\7\5\0"+
    "\4\7\3\0\1\7\23\0\1\145\27\7\5\0\4\7"+
    "\3\0\1\7\23\0\1\7\1\146\26\7\5\0\4\7"+
    "\3\0\1\7\23\0\1\147\27\7\5\0\4\7\3\0"+
    "\1\7\23\0\6\7\1\150\21\7\5\0\4\7\3\0"+
    "\1\7\23\0\1\7\1\151\26\7\5\0\4\7\3\0"+
    "\1\7\23\0\4\7\1\152\6\7\1\153\4\7\1\154"+
    "\7\7\5\0\4\7\3\0\1\7\23\0\4\7\1\155"+
    "\23\7\5\0\4\7\3\0\1\7\23\0\23\7\1\156"+
    "\4\7\5\0\4\7\3\0\1\7\23\0\2\7\1\157"+
    "\1\160\2\7\1\161\21\7\5\0\4\7\3\0\1\7"+
    "\23\0\20\7\1\162\7\7\5\0\4\7\3\0\1\7"+
    "\23\0\6\7\1\163\21\7\5\0\4\7\3\0\1\7"+
    "\23\0\4\7\1\164\23\7\5\0\4\7\3\0\1\7"+
    "\23\0\20\7\1\165\7\7\5\0\4\7\3\0\1\7"+
    "\23\0\6\7\1\166\21\7\5\0\4\7\3\0\1\7"+
    "\23\0\4\7\1\167\23\7\5\0\4\7\3\0\1\7"+
    "\23\0\13\7\1\170\14\7\5\0\4\7\3\0\1\7"+
    "\23\0\5\7\1\171\22\7\5\0\4\7\3\0\1\7"+
    "\23\0\11\7\1\172\16\7\5\0\4\7\3\0\1\7"+
    "\23\0\1\7\1\173\2\7\1\174\23\7\5\0\4\7"+
    "\3\0\1\7\23\0\1\175\27\7\5\0\4\7\3\0"+
    "\1\7\23\0\4\7\1\176\23\7\5\0\4\7\3\0"+
    "\1\7\23\0\16\7\1\177\11\7\5\0\4\7\3\0"+
    "\1\7\23\0\21\7\1\200\6\7\5\0\4\7\3\0"+
    "\1\7\23\0\12\7\1\201\7\7\1\202\5\7\5\0"+
    "\4\7\3\0\1\7\23\0\6\7\1\203\21\7\5\0"+
    "\4\7\3\0\1\7\23\0\15\7\1\204\12\7\5\0"+
    "\4\7\3\0\1\7\23\0\4\7\1\205\23\7\5\0"+
    "\4\7\3\0\1\7\23\0\2\7\1\206\25\7\5\0"+
    "\4\7\3\0\1\7\23\0\6\7\1\207\21\7\5\0"+
    "\4\7\3\0\1\7\23\0\20\7\1\210\7\7\5\0"+
    "\4\7\3\0\1\7\23\0\5\7\1\211\22\7\5\0"+
    "\4\7\3\0\1\7\23\0\20\7\1\212\7\7\5\0"+
    "\4\7\3\0\1\7\23\0\2\7\1\213\25\7\5\0"+
    "\4\7\3\0\1\7\23\0\2\7\1\214\25\7\5\0"+
    "\4\7\3\0\1\7\23\0\2\7\1\215\25\7\5\0"+
    "\4\7\3\0\1\7\23\0\21\7\1\216\6\7\5\0"+
    "\4\7\3\0\1\7\23\0\10\7\1\217\17\7\5\0"+
    "\4\7\3\0\1\7\23\0\12\7\1\220\15\7\5\0"+
    "\4\7\3\0\1\7\23\0\21\7\1\221\6\7\5\0"+
    "\4\7\3\0\1\7\23\0\1\7\1\222\26\7\5\0"+
    "\4\7\3\0\1\7\23\0\2\7\1\223\25\7\5\0"+
    "\4\7\3\0\1\7\23\0\11\7\1\224\16\7\5\0"+
    "\4\7\3\0\1\7\23\0\2\7\1\225\25\7\5\0"+
    "\4\7\3\0\1\7\23\0\11\7\1\226\7\7\1\227"+
    "\6\7\5\0\4\7\3\0\1\7\23\0\11\7\1\230"+
    "\16\7\5\0\4\7\3\0\1\7\23\0\1\231\27\7"+
    "\5\0\4\7\3\0\1\7\23\0\11\7\1\232\16\7"+
    "\5\0\4\7\3\0\1\7\23\0\2\7\1\233\25\7"+
    "\5\0\4\7\3\0\1\7\23\0\13\7\1\234\14\7"+
    "\5\0\4\7\3\0\1\7\23\0\1\7\1\235\26\7"+
    "\5\0\4\7\3\0\1\7\23\0\1\236\27\7\5\0"+
    "\4\7\3\0\1\7\23\0\22\7\1\237\5\7\5\0"+
    "\4\7\3\0\1\7\23\0\1\240\27\7\5\0\4\7"+
    "\3\0\1\7\23\0\20\7\1\241\7\7\5\0\4\7"+
    "\3\0\1\7\23\0\12\7\1\242\15\7\5\0\4\7"+
    "\3\0\1\7\23\0\10\7\1\243\17\7\5\0\4\7"+
    "\3\0\1\7\23\0\3\7\1\244\24\7\5\0\4\7"+
    "\3\0\1\7\23\0\4\7\1\245\23\7\5\0\4\7"+
    "\3\0\1\7\23\0\2\7\1\246\25\7\5\0\4\7"+
    "\3\0\1\7\23\0\12\7\1\247\15\7\5\0\4\7"+
    "\3\0\1\7\23\0\12\7\1\250\15\7\5\0\4\7"+
    "\3\0\1\7\23\0\20\7\1\251\7\7\5\0\4\7"+
    "\3\0\1\7\23\0\3\7\1\252\24\7\5\0\4\7"+
    "\3\0\1\7\23\0\3\7\1\253\24\7\5\0\4\7"+
    "\3\0\1\7\23\0\5\7\1\254\22\7\5\0\4\7"+
    "\3\0\1\7\23\0\26\7\1\255\1\7\5\0\4\7"+
    "\3\0\1\7\23\0\2\7\1\256\25\7\5\0\4\7"+
    "\3\0\1\7\23\0\3\7\1\257\24\7\5\0\4\7"+
    "\3\0\1\7\23\0\2\7\1\260\25\7\5\0\4\7"+
    "\3\0\1\7\23\0\3\7\1\261\24\7\5\0\4\7"+
    "\3\0\1\7\23\0\4\7\1\262\23\7\5\0\4\7"+
    "\3\0\1\7\23\0\11\7\1\263\16\7\5\0\4\7"+
    "\3\0\1\7\23\0\14\7\1\264\13\7\5\0\4\7"+
    "\3\0\1\7\23\0\1\7\1\265\26\7\5\0\4\7"+
    "\3\0\1\7\23\0\11\7\1\266\16\7\5\0\4\7"+
    "\3\0\1\7\23\0\21\7\1\267\6\7\5\0\4\7"+
    "\3\0\1\7\23\0\4\7\1\270\23\7\5\0\4\7"+
    "\3\0\1\7\23\0\11\7\1\271\16\7\5\0\4\7"+
    "\3\0\1\7\23\0\4\7\1\272\23\7\5\0\4\7"+
    "\3\0\1\7\23\0\12\7\1\273\15\7\5\0\4\7"+
    "\3\0\1\7\23\0\1\7\1\274\26\7\5\0\4\7"+
    "\3\0\1\7\23\0\15\7\1\275\12\7\5\0\4\7"+
    "\3\0\1\7\23\0\4\7\1\276\23\7\5\0\4\7"+
    "\3\0\1\7\23\0\4\7\1\277\23\7\5\0\4\7"+
    "\3\0\1\7\23\0\12\7\1\300\15\7\5\0\4\7"+
    "\3\0\1\7\23\0\27\7\1\301\5\0\4\7\3\0"+
    "\1\7\23\0\16\7\1\302\11\7\5\0\4\7\3\0"+
    "\1\7\23\0\22\7\1\303\5\7\5\0\4\7\3\0"+
    "\1\7\23\0\4\7\1\304\23\7\5\0\4\7\3\0"+
    "\1\7\23\0\6\7\1\305\21\7\5\0\4\7\3\0"+
    "\1\7\23\0\11\7\1\306\16\7\5\0\4\7\3\0"+
    "\1\7\23\0\3\7\1\307\24\7\5\0\4\7\3\0"+
    "\1\7\23\0\11\7\1\310\16\7\5\0\4\7\3\0"+
    "\1\7\23\0\2\7\1\311\25\7\5\0\4\7\3\0"+
    "\1\7\23\0\15\7\1\312\12\7\5\0\4\7\3\0"+
    "\1\7\23\0\1\7\1\313\26\7\5\0\4\7\3\0"+
    "\1\7\23\0\6\7\1\314\21\7\5\0\4\7\3\0"+
    "\1\7\23\0\1\315\27\7\5\0\4\7\3\0\1\7"+
    "\23\0\2\7\1\316\25\7\5\0\4\7\3\0\1\7"+
    "\23\0\12\7\1\317\15\7\5\0\4\7\3\0\1\7"+
    "\23\0\23\7\1\320\4\7\5\0\4\7\3\0\1\7"+
    "\23\0\4\7\1\321\23\7\5\0\4\7\3\0\1\7"+
    "\23\0\12\7\1\322\15\7\5\0\4\7\3\0\1\7"+
    "\23\0\21\7\1\323\6\7\5\0\4\7\3\0\1\7"+
    "\23\0\13\7\1\324\14\7\5\0\4\7\3\0\1\7"+
    "\23\0\12\7\1\325\15\7\5\0\4\7\3\0\1\7"+
    "\23\0\12\7\1\326\15\7\5\0\4\7\3\0\1\7"+
    "\23\0\2\7\1\327\25\7\5\0\4\7\3\0\1\7"+
    "\23\0\4\7\1\330\23\7\5\0\4\7\3\0\1\7"+
    "\23\0\1\7\1\331\26\7\4\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[8064];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\1\10\2\0\3\1\4\11\2\1\1\11\1\1"+
    "\2\11\1\1\3\11\2\1\2\11\1\1\4\11\20\1"+
    "\3\11\1\1\20\11\1\0\35\1\2\11\166\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[217];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
  String pstring = new String();
  public int line_num() { return (yyline+1); }
  public String buff() {return new String(zzBuffer,zzCurrentPos,10).trim();}


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Yylex(java.io.Reader in) {
    this.zzReader = in;
  }



  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          zzR = false;
          break;
        case '\r':
          yyline++;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
          }
          break;
        default:
          zzR = false;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { return new Symbol(sym.UIdent, yytext().intern());
            }
          case 86: break;
          case 2: 
            { return new Symbol(sym.LIdent, yytext().intern());
            }
          case 87: break;
          case 3: 
            { return new Symbol(sym._INTEGER_, new Integer(yytext()));
            }
          case 88: break;
          case 4: 
            { return new Symbol(sym._SYMB_0);
            }
          case 89: break;
          case 5: 
            { return new Symbol(sym._SYMB_1);
            }
          case 90: break;
          case 6: 
            { return new Symbol(sym._SYMB_2);
            }
          case 91: break;
          case 7: 
            { return new Symbol(sym._SYMB_3);
            }
          case 92: break;
          case 8: 
            { return new Symbol(sym._SYMB_4);
            }
          case 93: break;
          case 9: 
            { return new Symbol(sym._SYMB_5);
            }
          case 94: break;
          case 10: 
            { return new Symbol(sym._SYMB_6);
            }
          case 95: break;
          case 11: 
            { return new Symbol(sym._SYMB_7);
            }
          case 96: break;
          case 12: 
            { return new Symbol(sym._SYMB_8);
            }
          case 97: break;
          case 13: 
            { return new Symbol(sym._SYMB_9);
            }
          case 98: break;
          case 14: 
            { return new Symbol(sym._SYMB_10);
            }
          case 99: break;
          case 15: 
            { return new Symbol(sym._SYMB_11);
            }
          case 100: break;
          case 16: 
            { return new Symbol(sym._SYMB_12);
            }
          case 101: break;
          case 17: 
            { return new Symbol(sym._SYMB_14);
            }
          case 102: break;
          case 18: 
            { return new Symbol(sym._SYMB_15);
            }
          case 103: break;
          case 19: 
            { return new Symbol(sym._SYMB_29);
            }
          case 104: break;
          case 20: 
            { return new Symbol(sym._SYMB_22);
            }
          case 105: break;
          case 21: 
            { return new Symbol(sym._SYMB_23);
            }
          case 106: break;
          case 22: 
            { return new Symbol(sym._SYMB_24);
            }
          case 107: break;
          case 23: 
            { return new Symbol(sym._SYMB_25);
            }
          case 108: break;
          case 24: 
            { return new Symbol(sym._SYMB_26);
            }
          case 109: break;
          case 25: 
            { return new Symbol(sym._SYMB_27);
            }
          case 110: break;
          case 26: 
            { return new Symbol(sym._SYMB_28);
            }
          case 111: break;
          case 27: 
            { /* ignore white space. */
            }
          case 112: break;
          case 28: 
            { yybegin(STRING);
            }
          case 113: break;
          case 29: 
            { 
            }
          case 114: break;
          case 30: 
            { pstring += yytext();
            }
          case 115: break;
          case 31: 
            { String foo = pstring; pstring = new String(); yybegin(YYINITIAL); return new Symbol(sym._STRING_, foo.intern());
            }
          case 116: break;
          case 32: 
            { yybegin(ESCAPED);
            }
          case 117: break;
          case 33: 
            { pstring += yytext(); yybegin(STRING);
            }
          case 118: break;
          case 34: 
            { pstring += "\t"; yybegin(STRING);
            }
          case 119: break;
          case 35: 
            { pstring +=  "\n"; yybegin(STRING);
            }
          case 120: break;
          case 36: 
            { pstring += "\""; yybegin(STRING);
            }
          case 121: break;
          case 37: 
            { pstring += "\\"; yybegin(STRING);
            }
          case 122: break;
          case 38: 
            { return new Symbol(sym._SYMB_20);
            }
          case 123: break;
          case 39: 
            { return new Symbol(sym._SYMB_21);
            }
          case 124: break;
          case 40: 
            { return new Symbol(sym._SYMB_13);
            }
          case 125: break;
          case 41: 
            { return new Symbol(sym._SYMB_18);
            }
          case 126: break;
          case 42: 
            { return new Symbol(sym._SYMB_16);
            }
          case 127: break;
          case 43: 
            { return new Symbol(sym._SYMB_17);
            }
          case 128: break;
          case 44: 
            { return new Symbol(sym._SYMB_19);
            }
          case 129: break;
          case 45: 
            { yybegin(COMMENT);
            }
          case 130: break;
          case 46: 
            { return new Symbol(sym._SYMB_49);
            }
          case 131: break;
          case 47: 
            { return new Symbol(sym._SYMB_46);
            }
          case 132: break;
          case 48: 
            { yybegin(YYINITIAL);
            }
          case 133: break;
          case 49: 
            { /* BNFC single-line comment */
            }
          case 134: break;
          case 50: 
            { return new Symbol(sym._SYMB_65);
            }
          case 135: break;
          case 51: 
            { return new Symbol(sym._SYMB_51);
            }
          case 136: break;
          case 52: 
            { return new Symbol(sym._SYMB_54);
            }
          case 137: break;
          case 53: 
            { return new Symbol(sym._SYMB_37);
            }
          case 138: break;
          case 54: 
            { return new Symbol(sym._SYMB_45);
            }
          case 139: break;
          case 55: 
            { return new Symbol(sym._SYMB_58);
            }
          case 140: break;
          case 56: 
            { return new Symbol(sym._SYMB_38);
            }
          case 141: break;
          case 57: 
            { return new Symbol(sym._SYMB_61);
            }
          case 142: break;
          case 58: 
            { return new Symbol(sym._SYMB_62);
            }
          case 143: break;
          case 59: 
            { return new Symbol(sym._SYMB_66);
            }
          case 144: break;
          case 60: 
            { return new Symbol(sym._SYMB_55);
            }
          case 145: break;
          case 61: 
            { return new Symbol(sym._SYMB_33);
            }
          case 146: break;
          case 62: 
            { return new Symbol(sym._SYMB_36);
            }
          case 147: break;
          case 63: 
            { return new Symbol(sym._SYMB_44);
            }
          case 148: break;
          case 64: 
            { return new Symbol(sym._SYMB_31);
            }
          case 149: break;
          case 65: 
            { return new Symbol(sym._SYMB_64);
            }
          case 150: break;
          case 66: 
            { return new Symbol(sym._SYMB_67);
            }
          case 151: break;
          case 67: 
            { return new Symbol(sym._SYMB_52);
            }
          case 152: break;
          case 68: 
            { return new Symbol(sym._SYMB_34);
            }
          case 153: break;
          case 69: 
            { return new Symbol(sym._SYMB_35);
            }
          case 154: break;
          case 70: 
            { return new Symbol(sym._SYMB_30);
            }
          case 155: break;
          case 71: 
            { return new Symbol(sym._SYMB_59);
            }
          case 156: break;
          case 72: 
            { return new Symbol(sym._SYMB_40);
            }
          case 157: break;
          case 73: 
            { return new Symbol(sym._SYMB_57);
            }
          case 158: break;
          case 74: 
            { return new Symbol(sym._SYMB_63);
            }
          case 159: break;
          case 75: 
            { return new Symbol(sym._SYMB_48);
            }
          case 160: break;
          case 76: 
            { return new Symbol(sym._SYMB_53);
            }
          case 161: break;
          case 77: 
            { return new Symbol(sym._SYMB_60);
            }
          case 162: break;
          case 78: 
            { return new Symbol(sym._SYMB_41);
            }
          case 163: break;
          case 79: 
            { return new Symbol(sym._SYMB_32);
            }
          case 164: break;
          case 80: 
            { return new Symbol(sym._SYMB_43);
            }
          case 165: break;
          case 81: 
            { return new Symbol(sym._SYMB_42);
            }
          case 166: break;
          case 82: 
            { return new Symbol(sym._SYMB_56);
            }
          case 167: break;
          case 83: 
            { return new Symbol(sym._SYMB_39);
            }
          case 168: break;
          case 84: 
            { return new Symbol(sym._SYMB_50);
            }
          case 169: break;
          case 85: 
            { return new Symbol(sym._SYMB_47);
            }
          case 170: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
